export const arabicAlphabet = [
  { id: "alif", arabicName: "ألف", polishName: "Alif", transliteration: "a / aa", forms: { isolated: "ا", initial: "ا", medial: "ـا", final: "ـا" }, pronunciation: "Długi lub krótki dźwięk a. Sama litera nie łączy się z następną po lewej stronie.", example: { ar: "إسلام", pl: "islam", tr: "islam" } },
  { id: "ba", arabicName: "باء", polishName: "Ba", transliteration: "b", forms: { isolated: "ب", initial: "بـ", medial: "ـبـ", final: "ـب" }, pronunciation: "Jak polskie b w słowie balon. Kropka znajduje się pod literą.", example: { ar: "باتيك", pl: "batik", tr: "batik" } },
  { id: "ta", arabicName: "تاء", polishName: "Ta", transliteration: "t", forms: { isolated: "ت", initial: "تـ", medial: "ـتـ", final: "ـت" }, pronunciation: "Jak polskie t. Dwie kropki są nad literą.", example: { ar: "تمر", pl: "daktyle", tr: "tamr" } },
  { id: "tha", arabicName: "ثاء", polishName: "Sa miękkie", transliteration: "th", forms: { isolated: "ث", initial: "ثـ", medial: "ـثـ", final: "ـث" }, pronunciation: "Jak angielskie th w think. Czubek języka lekko dotyka zębów.", example: { ar: "ثلج", pl: "śnieg", tr: "thalj" } },
  { id: "jim", arabicName: "جيم", polishName: "Dżim", transliteration: "j", forms: { isolated: "ج", initial: "جـ", medial: "ـجـ", final: "ـج" }, pronunciation: "Najczęściej jak polskie dż w dżem.", example: { ar: "جاوة", pl: "Jawa", tr: "jawa" } },
  { id: "ha", arabicName: "حاء", polishName: "Ha gardłowe", transliteration: "h", forms: { isolated: "ح", initial: "حـ", medial: "ـحـ", final: "ـح" }, pronunciation: "Mocne, bezdźwięczne h z gardła. Nie ma polskiego odpowiednika.", example: { ar: "حلال", pl: "halal", tr: "halal" } },
  { id: "kha", arabicName: "خاء", polishName: "Cha", transliteration: "kh", forms: { isolated: "خ", initial: "خـ", medial: "ـخـ", final: "ـخ" }, pronunciation: "Jak polskie ch, ale głębiej w gardle.", example: { ar: "خبز", pl: "chleb", tr: "chubz" } },
  { id: "dal", arabicName: "دال", polishName: "Dal", transliteration: "d", forms: { isolated: "د", initial: "د", medial: "ـد", final: "ـد" }, pronunciation: "Jak polskie d. Nie łączy się z następną literą.", example: { ar: "دعاء", pl: "dua", tr: "du'a" } },
  { id: "dhal", arabicName: "ذال", polishName: "Zal", transliteration: "dh", forms: { isolated: "ذ", initial: "ذ", medial: "ـذ", final: "ـذ" }, pronunciation: "Jak angielskie th w this. Brzmi miękko, między d i z.", example: { ar: "ذهب", pl: "złoto", tr: "dhahab" } },
  { id: "ra", arabicName: "راء", polishName: "Ra", transliteration: "r", forms: { isolated: "ر", initial: "ر", medial: "ـر", final: "ـر" }, pronunciation: "Drżące r, podobne do polskiego. Nie łączy się z następną literą.", example: { ar: "رمضان", pl: "ramadan", tr: "ramadan" } },
  { id: "zay", arabicName: "زاي", polishName: "Zaj", transliteration: "z", forms: { isolated: "ز", initial: "ز", medial: "ـز", final: "ـز" }, pronunciation: "Jak polskie z. Nie łączy się z następną literą.", example: { ar: "زيارة", pl: "wizyta", tr: "zijara" } },
  { id: "sin", arabicName: "سين", polishName: "Sin", transliteration: "s", forms: { isolated: "س", initial: "سـ", medial: "ـسـ", final: "ـس" }, pronunciation: "Jak polskie s.", example: { ar: "سلام", pl: "pokój, salam", tr: "salam" } },
  { id: "shin", arabicName: "شين", polishName: "Szin", transliteration: "sh", forms: { isolated: "ش", initial: "شـ", medial: "ـشـ", final: "ـش" }, pronunciation: "Jak polskie sz.", example: { ar: "شمس", pl: "słońce", tr: "szams" } },
  { id: "sad", arabicName: "صاد", polishName: "Sad", transliteration: "s", forms: { isolated: "ص", initial: "صـ", medial: "ـصـ", final: "ـص" }, pronunciation: "Głębokie, ciemne s wymawiane z napięciem w jamie ustnej.", example: { ar: "صلاة", pl: "modlitwa", tr: "salat" } },
  { id: "dad", arabicName: "ضاد", polishName: "Dad", transliteration: "d", forms: { isolated: "ض", initial: "ضـ", medial: "ـضـ", final: "ـض" }, pronunciation: "Głębokie d, charakterystyczne dla arabskiego.", example: { ar: "ضيف", pl: "gość", tr: "dajf" } },
  { id: "ta_emph", arabicName: "طاء", polishName: "Ta głębokie", transliteration: "t", forms: { isolated: "ط", initial: "طـ", medial: "ـطـ", final: "ـط" }, pronunciation: "Głębokie, mocne t.", example: { ar: "طعام", pl: "jedzenie", tr: "ta'am" } },
  { id: "za_emph", arabicName: "ظاء", polishName: "Za głębokie", transliteration: "z / dh", forms: { isolated: "ظ", initial: "ظـ", medial: "ـظـ", final: "ـظ" }, pronunciation: "Głębokie brzmienie między z i angielskim th.", example: { ar: "ظاهر", pl: "widoczny", tr: "zahir" } },
  { id: "ayn", arabicName: "عين", polishName: "Ajn", transliteration: "'", forms: { isolated: "ع", initial: "عـ", medial: "ـعـ", final: "ـع" }, pronunciation: "Dźwięk gardłowy, jak napięte a zaczynane głęboko w gardle.", example: { ar: "علم", pl: "wiedza", tr: "'ilm" } },
  { id: "ghayn", arabicName: "غين", polishName: "Gajn", transliteration: "gh", forms: { isolated: "غ", initial: "غـ", medial: "ـغـ", final: "ـغ" }, pronunciation: "Dźwięczne, gardłowe r/ch, podobne do francuskiego r.", example: { ar: "غدانسك", pl: "Gdańsk", tr: "ghdansk" } },
  { id: "fa", arabicName: "فاء", polishName: "Fa", transliteration: "f", forms: { isolated: "ف", initial: "فـ", medial: "ـفـ", final: "ـف" }, pronunciation: "Jak polskie f.", example: { ar: "فجر", pl: "świt", tr: "fadżr" } },
  { id: "qaf", arabicName: "قاف", polishName: "Kaf głębokie", transliteration: "q", forms: { isolated: "ق", initial: "قـ", medial: "ـقـ", final: "ـق" }, pronunciation: "Głębokie k wymawiane z tyłu języka.", example: { ar: "قرآن", pl: "Koran", tr: "qur'an" } },
  { id: "kaf", arabicName: "كاف", polishName: "Kaf", transliteration: "k", forms: { isolated: "ك", initial: "كـ", medial: "ـكـ", final: "ـك" }, pronunciation: "Jak polskie k.", example: { ar: "كتاب", pl: "książka", tr: "kitab" } },
  { id: "lam", arabicName: "لام", polishName: "Lam", transliteration: "l", forms: { isolated: "ل", initial: "لـ", medial: "ـلـ", final: "ـل" }, pronunciation: "Jak polskie l.", example: { ar: "لوبلين", pl: "Lublin", tr: "lublin" } },
  { id: "mim", arabicName: "ميم", polishName: "Mim", transliteration: "m", forms: { isolated: "م", initial: "مـ", medial: "ـمـ", final: "ـم" }, pronunciation: "Jak polskie m.", example: { ar: "مسجد", pl: "meczet", tr: "masdżid" } },
  { id: "nun", arabicName: "نون", polishName: "Nun", transliteration: "n", forms: { isolated: "ن", initial: "نـ", medial: "ـنـ", final: "ـن" }, pronunciation: "Jak polskie n.", example: { ar: "إندونيسيا", pl: "Indonezja", tr: "indunisia" } },
  { id: "ha2", arabicName: "هاء", polishName: "Ha lekkie", transliteration: "h", forms: { isolated: "ه", initial: "هـ", medial: "ـهـ", final: "ـه" }, pronunciation: "Lekkie h, podobne do polskiego h w herbata.", example: { ar: "هلال", pl: "półksiężyc", tr: "hilal" } },
  { id: "waw", arabicName: "واو", polishName: "Ław", transliteration: "w / u", forms: { isolated: "و", initial: "و", medial: "ـو", final: "ـو" }, pronunciation: "Jak angielskie w albo długie u. Nie łączy się z następną literą.", example: { ar: "وارسو", pl: "Warszawa", tr: "warsaw" } },
  { id: "ya", arabicName: "ياء", polishName: "Ja", transliteration: "y / i", forms: { isolated: "ي", initial: "يـ", medial: "ـيـ", final: "ـي" }, pronunciation: "Jak j albo długie i.", example: { ar: "يوغياكارتا", pl: "Yogyakarta", tr: "jogyakarta" } }
];

export const words = [
  { id: "mama", ar: "ماما", tr: "mama", pl: "mama" },
  { id: "baba", ar: "بابا", tr: "baba", pl: "tata / baba" },
  { id: "kitab", ar: "كتاب", tr: "kitab", pl: "książka" },
  { id: "bait", ar: "بيت", tr: "bajt", pl: "dom" },
  { id: "shams", ar: "شمس", tr: "szams", pl: "słońce" },
  { id: "qamar", ar: "قمر", tr: "kamar", pl: "księżyc" },
  { id: "salam", ar: "سلام", tr: "salam", pl: "pokój / cześć" },
  { id: "islam", ar: "إسلام", tr: "islam", pl: "islam" },
  { id: "quran", ar: "قرآن", tr: "Koran", pl: "Koran" },
  { id: "masjid", ar: "مسجد", tr: "masdżid", pl: "meczet" },
  { id: "polska", ar: "بولندا", tr: "bulanda", pl: "Polska" },
  { id: "warsaw", ar: "وارسو", tr: "warsaw", pl: "Warszawa" },
  { id: "lublin", ar: "لوبلين", tr: "lublin", pl: "Lublin" },
  { id: "indonesia", ar: "إندونيسيا", tr: "indunisia", pl: "Indonezja" },
  { id: "batik", ar: "باتيك", tr: "batik", pl: "batik" },
  { id: "borobudur", ar: "بوروبودور", tr: "borobudur", pl: "Borobudur" },
  { id: "orangutan", ar: "أورانغوتان", tr: "orangutan", pl: "orangutan" },
  { id: "pierogi", ar: "بيروغي", tr: "pierogi", pl: "pierogi" },
  { id: "zloty", ar: "زلوتي", tr: "zloty", pl: "złoty" },
  { id: "halal", ar: "حلال", tr: "halal", pl: "halal" },
  { id: "rahma", ar: "رحمة", tr: "rahma", pl: "miłosierdzie" },
  { id: "nur", ar: "نور", tr: "nur", pl: "światło" },
  { id: "woda", ar: "ماء", tr: "ma", pl: "woda" },
  { id: "ryz", ar: "أرز", tr: "aruzz", pl: "ryż" }
];

export const quranSurahs = [
  { number: 1, arName: "الفاتحة", enName: "Al-Fatihah", meaning: "The Opening" },
  { number: 2, arName: "البقرة", enName: "Al-Baqarah", meaning: "The Cow" },
  { number: 3, arName: "آل عمران", enName: "Ali 'Imran", meaning: "Family of Imran" },
  { number: 4, arName: "النساء", enName: "An-Nisa", meaning: "The Women" },
  { number: 5, arName: "المائدة", enName: "Al-Ma'idah", meaning: "The Table Spread" },
  { number: 6, arName: "الأنعام", enName: "Al-An'am", meaning: "The Cattle" },
  { number: 7, arName: "الأعراف", enName: "Al-A'raf", meaning: "The Heights" },
  { number: 8, arName: "الأنفال", enName: "Al-Anfal", meaning: "The Spoils of War" },
  { number: 9, arName: "التوبة", enName: "At-Tawbah", meaning: "The Repentance" },
  { number: 10, arName: "يونس", enName: "Yunus", meaning: "Jonah" },
  { number: 11, arName: "هود", enName: "Hud", meaning: "Hud" },
  { number: 12, arName: "يوسف", enName: "Yusuf", meaning: "Joseph" },
  { number: 13, arName: "الرعد", enName: "Ar-Ra'd", meaning: "The Thunder" },
  { number: 14, arName: "إبراهيم", enName: "Ibrahim", meaning: "Abraham" },
  { number: 15, arName: "الحجر", enName: "Al-Hijr", meaning: "The Rocky Tract" },
  { number: 16, arName: "النحل", enName: "An-Nahl", meaning: "The Bee" },
  { number: 17, arName: "الإسراء", enName: "Al-Isra", meaning: "The Night Journey" },
  { number: 18, arName: "الكهف", enName: "Al-Kahf", meaning: "The Cave" },
  { number: 19, arName: "مريم", enName: "Maryam", meaning: "Mary" },
  { number: 20, arName: "طه", enName: "Ta-Ha", meaning: "Ta-Ha" },
  { number: 21, arName: "الأنبياء", enName: "Al-Anbiya", meaning: "The Prophets" },
  { number: 22, arName: "الحج", enName: "Al-Hajj", meaning: "The Pilgrimage" },
  { number: 23, arName: "المؤمنون", enName: "Al-Mu'minun", meaning: "The Believers" },
  { number: 24, arName: "النور", enName: "An-Nur", meaning: "The Light" },
  { number: 25, arName: "الفرقان", enName: "Al-Furqan", meaning: "The Criterion" },
  { number: 26, arName: "الشعراء", enName: "Ash-Shu'ara", meaning: "The Poets" },
  { number: 27, arName: "النمل", enName: "An-Naml", meaning: "The Ant" },
  { number: 28, arName: "القصص", enName: "Al-Qasas", meaning: "The Stories" },
  { number: 29, arName: "العنكبوت", enName: "Al-'Ankabut", meaning: "The Spider" },
  { number: 30, arName: "الروم", enName: "Ar-Rum", meaning: "The Romans" },
  { number: 31, arName: "لقمان", enName: "Luqman", meaning: "Luqman" },
  { number: 32, arName: "السجدة", enName: "As-Sajdah", meaning: "The Prostration" },
  { number: 33, arName: "الأحزاب", enName: "Al-Ahzab", meaning: "The Combined Forces" },
  { number: 34, arName: "سبأ", enName: "Saba", meaning: "Sheba" },
  { number: 35, arName: "فاطر", enName: "Fatir", meaning: "Originator" },
  { number: 36, arName: "يس", enName: "Ya-Sin", meaning: "Ya Sin" },
  { number: 37, arName: "الصافات", enName: "As-Saffat", meaning: "Those Who Set the Ranks" },
  { number: 38, arName: "ص", enName: "Sad", meaning: "The Letter Sad" },
  { number: 39, arName: "الزمر", enName: "Az-Zumar", meaning: "The Troops" },
  { number: 40, arName: "غافر", enName: "Ghafir", meaning: "The Forgiver" },
  { number: 41, arName: "فصلت", enName: "Fussilat", meaning: "Explained in Detail" },
  { number: 42, arName: "الشورى", enName: "Ash-Shura", meaning: "The Consultation" },
  { number: 43, arName: "الزخرف", enName: "Az-Zukhruf", meaning: "The Ornaments of Gold" },
  { number: 44, arName: "الدخان", enName: "Ad-Dukhan", meaning: "The Smoke" },
  { number: 45, arName: "الجاثية", enName: "Al-Jathiyah", meaning: "The Crouching" },
  { number: 46, arName: "الأحقاف", enName: "Al-Ahqaf", meaning: "The Wind-Curved Sandhills" },
  { number: 47, arName: "محمد", enName: "Muhammad", meaning: "Muhammad" },
  { number: 48, arName: "الفتح", enName: "Al-Fath", meaning: "The Victory" },
  { number: 49, arName: "الحجرات", enName: "Al-Hujurat", meaning: "The Rooms" },
  { number: 50, arName: "ق", enName: "Qaf", meaning: "The Letter Qaf" },
  { number: 51, arName: "الذاريات", enName: "Adh-Dhariyat", meaning: "The Winnowing Winds" },
  { number: 52, arName: "الطور", enName: "At-Tur", meaning: "The Mount" },
  { number: 53, arName: "النجم", enName: "An-Najm", meaning: "The Star" },
  { number: 54, arName: "القمر", enName: "Al-Qamar", meaning: "The Moon" },
  { number: 55, arName: "الرحمن", enName: "Ar-Rahman", meaning: "The Beneficent" },
  { number: 56, arName: "الواقعة", enName: "Al-Waqi'ah", meaning: "The Inevitable" },
  { number: 57, arName: "الحديد", enName: "Al-Hadid", meaning: "The Iron" },
  { number: 58, arName: "المجادلة", enName: "Al-Mujadila", meaning: "The Pleading Woman" },
  { number: 59, arName: "الحشر", enName: "Al-Hashr", meaning: "The Exile" },
  { number: 60, arName: "الممتحنة", enName: "Al-Mumtahanah", meaning: "She That Is Examined" },
  { number: 61, arName: "الصف", enName: "As-Saf", meaning: "The Ranks" },
  { number: 62, arName: "الجمعة", enName: "Al-Jumu'ah", meaning: "Friday" },
  { number: 63, arName: "المنافقون", enName: "Al-Munafiqun", meaning: "The Hypocrites" },
  { number: 64, arName: "التغابن", enName: "At-Taghabun", meaning: "The Mutual Disillusion" },
  { number: 65, arName: "الطلاق", enName: "At-Talaq", meaning: "The Divorce" },
  { number: 66, arName: "التحريم", enName: "At-Tahrim", meaning: "The Prohibition" },
  { number: 67, arName: "الملك", enName: "Al-Mulk", meaning: "The Sovereignty" },
  { number: 68, arName: "القلم", enName: "Al-Qalam", meaning: "The Pen" },
  { number: 69, arName: "الحاقة", enName: "Al-Haqqah", meaning: "The Reality" },
  { number: 70, arName: "المعارج", enName: "Al-Ma'arij", meaning: "The Ascending Stairways" },
  { number: 71, arName: "نوح", enName: "Nuh", meaning: "Noah" },
  { number: 72, arName: "الجن", enName: "Al-Jinn", meaning: "The Jinn" },
  { number: 73, arName: "المزمل", enName: "Al-Muzzammil", meaning: "The Enshrouded One" },
  { number: 74, arName: "المدثر", enName: "Al-Muddaththir", meaning: "The Cloaked One" },
  { number: 75, arName: "القيامة", enName: "Al-Qiyamah", meaning: "The Resurrection" },
  { number: 76, arName: "الإنسان", enName: "Al-Insan", meaning: "The Man" },
  { number: 77, arName: "المرسلات", enName: "Al-Mursalat", meaning: "The Emissaries" },
  { number: 78, arName: "النبأ", enName: "An-Naba", meaning: "The Tidings" },
  { number: 79, arName: "النازعات", enName: "An-Nazi'at", meaning: "Those Who Drag Forth" },
  { number: 80, arName: "عبس", enName: "'Abasa", meaning: "He Frowned" },
  { number: 81, arName: "التكوير", enName: "At-Takwir", meaning: "The Overthrowing" },
  { number: 82, arName: "الانفطار", enName: "Al-Infitar", meaning: "The Cleaving" },
  { number: 83, arName: "المطففين", enName: "Al-Mutaffifin", meaning: "The Defrauding" },
  { number: 84, arName: "الانشقاق", enName: "Al-Inshiqaq", meaning: "The Sundering" },
  { number: 85, arName: "البروج", enName: "Al-Buruj", meaning: "The Mansions of the Stars" },
  { number: 86, arName: "الطارق", enName: "At-Tariq", meaning: "The Nightcomer" },
  { number: 87, arName: "الأعلى", enName: "Al-A'la", meaning: "The Most High" },
  { number: 88, arName: "الغاشية", enName: "Al-Ghashiyah", meaning: "The Overwhelming" },
  { number: 89, arName: "الفجر", enName: "Al-Fajr", meaning: "The Dawn" },
  { number: 90, arName: "البلد", enName: "Al-Balad", meaning: "The City" },
  { number: 91, arName: "الشمس", enName: "Ash-Shams", meaning: "The Sun" },
  { number: 92, arName: "الليل", enName: "Al-Layl", meaning: "The Night" },
  { number: 93, arName: "الضحى", enName: "Ad-Duha", meaning: "The Morning Hours" },
  { number: 94, arName: "الشرح", enName: "Ash-Sharh", meaning: "The Relief" },
  { number: 95, arName: "التين", enName: "At-Tin", meaning: "The Fig" },
  { number: 96, arName: "العلق", enName: "Al-'Alaq", meaning: "The Clot" },
  { number: 97, arName: "القدر", enName: "Al-Qadr", meaning: "The Power" },
  { number: 98, arName: "البينة", enName: "Al-Bayyinah", meaning: "The Clear Proof" },
  { number: 99, arName: "الزلزلة", enName: "Az-Zalzalah", meaning: "The Earthquake" },
  { number: 100, arName: "العاديات", enName: "Al-'Adiyat", meaning: "The Courser" },
  { number: 101, arName: "القارعة", enName: "Al-Qari'ah", meaning: "The Calamity" },
  { number: 102, arName: "التكاثر", enName: "At-Takathur", meaning: "The Rivalry in World Increase" },
  { number: 103, arName: "العصر", enName: "Al-'Asr", meaning: "The Declining Day" },
  { number: 104, arName: "الهمزة", enName: "Al-Humazah", meaning: "The Traducer" },
  { number: 105, arName: "الفيل", enName: "Al-Fil", meaning: "The Elephant" },
  { number: 106, arName: "قريش", enName: "Quraysh", meaning: "Quraysh" },
  { number: 107, arName: "الماعون", enName: "Al-Ma'un", meaning: "The Small Kindnesses" },
  { number: 108, arName: "الكوثر", enName: "Al-Kawthar", meaning: "The Abundance" },
  { number: 109, arName: "الكافرون", enName: "Al-Kafirun", meaning: "The Disbelievers" },
  { number: 110, arName: "النصر", enName: "An-Nasr", meaning: "The Divine Support" },
  { number: 111, arName: "المسد", enName: "Al-Masad", meaning: "The Palm Fiber" },
  { number: 112, arName: "الإخلاص", enName: "Al-Ikhlas", meaning: "The Sincerity" },
  { number: 113, arName: "الفلق", enName: "Al-Falaq", meaning: "The Daybreak" },
  { number: 114, arName: "الناس", enName: "An-Nas", meaning: "Mankind" }
];

export const dailyTasks = [
  "Poznaj 3 nowe litery i kliknij każdą z nich.",
  "Zrób 7 fiszek w trybie powtórek.",
  "Przećwicz wymowę słowa سلام.",
  "Narysuj literę ب na canvasie.",
  "Zagraj jedną rundę Memory Match."
];
