export const arabicAlphabet = [
  { id: "alif", arabicName: "ألف", polishName: "Alif", transliteration: "a / aa", forms: { isolated: "ا", initial: "ا", medial: "ـا", final: "ـا" }, pronunciation: "Długi lub krótki dźwięk a. Sama litera nie łączy się z następną po lewej stronie.", example: { ar: "إسلام", pl: "islam", tr: "islam" } },
  { id: "ba", arabicName: "باء", polishName: "Ba", transliteration: "b", forms: { isolated: "ب", initial: "بـ", medial: "ـبـ", final: "ـب" }, pronunciation: "Jak polskie b w słowie balon. Kropka znajduje się pod literą.", example: { ar: "باتيك", pl: "batik", tr: "batik" } },
  { id: "ta", arabicName: "تاء", polishName: "Ta", transliteration: "t", forms: { isolated: "ت", initial: "تـ", medial: "ـتـ", final: "ـت" }, pronunciation: "Jak polskie t. Dwie kropki są nad literą.", example: { ar: "تمر", pl: "daktyle", tr: "tamr" } },
  { id: "tha", arabicName: "ثاء", polishName: "Sa miękkie", transliteration: "th", forms: { isolated: "ث", initial: "ثـ", medial: "ـثـ", final: "ـث" }, pronunciation: "Jak angielskie th w think. Czubek języka lekko dotyka zębów.", example: { ar: "ثلج", pl: "śnieg", tr: "thalj" } },
  { id: "jim", arabicName: "جيم", polishName: "Dżim", transliteration: "j", forms: { isolated: "ج", initial: "جـ", medial: "ـجـ", final: "ـج" }, pronunciation: "Najczęściej jak polskie dż w dżem.", example: { ar: "جاوة", pl: "Jawa", tr: "jawa" } },
  { id: "ha", arabicName: "حاء", polishName: "Ha gardłowe", transliteration: "h", forms: { isolated: "ح", initial: "حـ", medial: "ـحـ", final: "ـح" }, pronunciation: "Mocne, bezdźwięczne h z gardła. Nie ma polskiego odpowiednika.", example: { ar: "حلال", pl: "halal", tr: "halal" } },
  { id: "kha", arabicName: "خاء", polishName: "Cha", transliteration: "kh", forms: { isolated: "خ", initial: "خـ", medial: "ـخـ", final: "ـخ" }, pronunciation: "Jak polskie ch, ale głębiej w gardle.", example: { ar: "خبز", pl: "chleb", tr: "chubz" } },
  { id: "dal", arabicName: "دال", polishName: "Dal", transliteration: "d", forms: { isolated: "د", initial: "د", medial: "ـد", final: "ـد" }, pronunciation: "Jak polskie d. Nie łączy się z następną literą.", example: { ar: "دعاء", pl: "dua", tr: "du'a" } },
  { id: "dhal", arabicName: "ذال", polishName: "Zal", transliteration: "dh", forms: { isolated: "ذ", initial: "ذ", medial: "ـذ", final: "ـذ" }, pronunciation: "Jak angielskie th w this. Brzmi miękko, między d i z.", example: { ar: "ذهب", pl: "złoto", tr: "dhahab" } },
  { id: "ra", arabicName: "راء", polishName: "Ra", transliteration: "r", forms: { isolated: "ر", initial: "ر", medial: "ـر", final: "ـر" }, pronunciation: "Drżące r, podobne do polskiego. Nie łączy się z następną literą.", example: { ar: "رمضان", pl: "ramadan", tr: "ramadan" } },
  { id: "zay", arabicName: "زاي", polishName: "Zaj", transliteration: "z", forms: { isolated: "ز", initial: "ز", medial: "ـز", final: "ـز" }, pronunciation: "Jak polskie z. Nie łączy się z następną literą.", example: { ar: "زيارة", pl: "wizyta", tr: "zijara" } },
  { id: "sin", arabicName: "سين", polishName: "Sin", transliteration: "s", forms: { isolated: "س", initial: "سـ", medial: "ـسـ", final: "ـس" }, pronunciation: "Jak polskie s.", example: { ar: "سلام", pl: "pokój, salam", tr: "salam" } },
  { id: "shin", arabicName: "شين", polishName: "Szin", transliteration: "sh", forms: { isolated: "ش", initial: "شـ", medial: "ـشـ", final: "ـش" }, pronunciation: "Jak polskie sz.", example: { ar: "شمس", pl: "słońce", tr: "szams" } },
  { id: "sad", arabicName: "صاد", polishName: "Sad", transliteration: "s", forms: { isolated: "ص", initial: "صـ", medial: "ـصـ", final: "ـص" }, pronunciation: "Głębokie, ciemne s wymawiane z napięciem w jamie ustnej.", example: { ar: "صلاة", pl: "modlitwa", tr: "salat" } },
  { id: "dad", arabicName: "ضاد", polishName: "Dad", transliteration: "d", forms: { isolated: "ض", initial: "ضـ", medial: "ـضـ", final: "ـض" }, pronunciation: "Głębokie d, charakterystyczne dla arabskiego.", example: { ar: "ضيف", pl: "gość", tr: "dajf" } },
  { id: "ta_emph", arabicName: "طاء", polishName: "Ta głębokie", transliteration: "t", forms: { isolated: "ط", initial: "طـ", medial: "ـطـ", final: "ـط" }, pronunciation: "Głębokie, mocne t.", example: { ar: "طعام", pl: "jedzenie", tr: "ta'am" } },
  { id: "za_emph", arabicName: "ظاء", polishName: "Za głębokie", transliteration: "z / dh", forms: { isolated: "ظ", initial: "ظـ", medial: "ـظـ", final: "ـظ" }, pronunciation: "Głębokie brzmienie między z i angielskim th.", example: { ar: "ظاهر", pl: "widoczny", tr: "zahir" } },
  { id: "ayn", arabicName: "عين", polishName: "Ajn", transliteration: "'", forms: { isolated: "ع", initial: "عـ", medial: "ـعـ", final: "ـع" }, pronunciation: "Dźwięk gardłowy, jak napięte a zaczynane głęboko w gardle.", example: { ar: "علم", pl: "wiedza", tr: "'ilm" } },
  { id: "ghayn", arabicName: "غين", polishName: "Gajn", transliteration: "gh", forms: { isolated: "غ", initial: "غـ", medial: "ـغـ", final: "ـغ" }, pronunciation: "Dźwięczne, gardłowe r/ch, podobne do francuskiego r.", example: { ar: "غدانسك", pl: "Gdańsk", tr: "ghdansk" } },
  { id: "fa", arabicName: "فاء", polishName: "Fa", transliteration: "f", forms: { isolated: "ف", initial: "فـ", medial: "ـفـ", final: "ـف" }, pronunciation: "Jak polskie f.", example: { ar: "فجر", pl: "świt", tr: "fadżr" } },
  { id: "qaf", arabicName: "قاف", polishName: "Kaf głębokie", transliteration: "q", forms: { isolated: "ق", initial: "قـ", medial: "ـقـ", final: "ـق" }, pronunciation: "Głębokie k wymawiane z tyłu języka.", example: { ar: "قرآن", pl: "Koran", tr: "qur'an" } },
  { id: "kaf", arabicName: "كاف", polishName: "Kaf", transliteration: "k", forms: { isolated: "ك", initial: "كـ", medial: "ـكـ", final: "ـك" }, pronunciation: "Jak polskie k.", example: { ar: "كتاب", pl: "książka", tr: "kitab" } },
  { id: "lam", arabicName: "لام", polishName: "Lam", transliteration: "l", forms: { isolated: "ل", initial: "لـ", medial: "ـلـ", final: "ـل" }, pronunciation: "Jak polskie l.", example: { ar: "لوبلين", pl: "Lublin", tr: "lublin" } },
  { id: "mim", arabicName: "ميم", polishName: "Mim", transliteration: "m", forms: { isolated: "م", initial: "مـ", medial: "ـمـ", final: "ـم" }, pronunciation: "Jak polskie m.", example: { ar: "مسجد", pl: "meczet", tr: "masdżid" } },
  { id: "nun", arabicName: "نون", polishName: "Nun", transliteration: "n", forms: { isolated: "ن", initial: "نـ", medial: "ـنـ", final: "ـن" }, pronunciation: "Jak polskie n.", example: { ar: "إندونيسيا", pl: "Indonezja", tr: "indunisia" } },
  { id: "ha2", arabicName: "هاء", polishName: "Ha lekkie", transliteration: "h", forms: { isolated: "ه", initial: "هـ", medial: "ـهـ", final: "ـه" }, pronunciation: "Lekkie h, podobne do polskiego h w herbata.", example: { ar: "هلال", pl: "półksiężyc", tr: "hilal" } },
  { id: "waw", arabicName: "واو", polishName: "Ław", transliteration: "w / u", forms: { isolated: "و", initial: "و", medial: "ـو", final: "ـو" }, pronunciation: "Jak angielskie w albo długie u. Nie łączy się z następną literą.", example: { ar: "وارسو", pl: "Warszawa", tr: "warsaw" } },
  { id: "ya", arabicName: "ياء", polishName: "Ja", transliteration: "y / i", forms: { isolated: "ي", initial: "يـ", medial: "ـيـ", final: "ـي" }, pronunciation: "Jak j albo długie i.", example: { ar: "يوغياكارتا", pl: "Yogyakarta", tr: "jogyakarta" } }
];

export const words = [
  { id: "mama", ar: "ماما", tr: "mama", pl: "mama" },
  { id: "baba", ar: "بابا", tr: "baba", pl: "tata / baba" },
  { id: "kitab", ar: "كتاب", tr: "kitab", pl: "książka" },
  { id: "bait", ar: "بيت", tr: "bajt", pl: "dom" },
  { id: "shams", ar: "شمس", tr: "szams", pl: "słońce" },
  { id: "qamar", ar: "قمر", tr: "kamar", pl: "księżyc" },
  { id: "salam", ar: "سلام", tr: "salam", pl: "pokój / cześć" },
  { id: "islam", ar: "إسلام", tr: "islam", pl: "islam" },
  { id: "quran", ar: "قرآن", tr: "Koran", pl: "Koran" },
  { id: "masjid", ar: "مسجد", tr: "masdżid", pl: "meczet" },
  { id: "polska", ar: "بولندا", tr: "bulanda", pl: "Polska" },
  { id: "warsaw", ar: "وارسو", tr: "warsaw", pl: "Warszawa" },
  { id: "lublin", ar: "لوبلين", tr: "lublin", pl: "Lublin" },
  { id: "indonesia", ar: "إندونيسيا", tr: "indunisia", pl: "Indonezja" },
  { id: "batik", ar: "باتيك", tr: "batik", pl: "batik" },
  { id: "borobudur", ar: "بوروبودور", tr: "borobudur", pl: "Borobudur" },
  { id: "orangutan", ar: "أورانغوتان", tr: "orangutan", pl: "orangutan" },
  { id: "pierogi", ar: "بيروغي", tr: "pierogi", pl: "pierogi" },
  { id: "zloty", ar: "زلوتي", tr: "zloty", pl: "złoty" },
  { id: "halal", ar: "حلال", tr: "halal", pl: "halal" },
  { id: "rahma", ar: "رحمة", tr: "rahma", pl: "miłosierdzie" },
  { id: "nur", ar: "نور", tr: "nur", pl: "światło" },
  { id: "woda", ar: "ماء", tr: "ma", pl: "woda" },
  { id: "ryz", ar: "أرز", tr: "aruzz", pl: "ryż" }
];

export const quranSurahs = [
  { number: 1, arName: "الفاتحة", enName: "Al-Fatihah", meaning: "The Opening" },
  { number: 2, arName: "البقرة", enName: "Al-Baqarah", meaning: "The Cow" },
  { number: 3, arName: "آل عمران", enName: "Ali 'Imran", meaning: "Family of Imran" },
  { number: 4, arName: "النساء", enName: "An-Nisa", meaning: "The Women" },
  { number: 5, arName: "المائدة", enName: "Al-Ma'idah", meaning: "The Table Spread" },
  { number: 6, arName: "الأنعام", enName: "Al-An'am", meaning: "The Cattle" },
  { number: 7, arName: "الأعراف", enName: "Al-A'raf", meaning: "The Heights" },
  { number: 8, arName: "الأنفال", enName: "Al-Anfal", meaning: "The Spoils of War" },
  { number: 9, arName: "التوبة", enName: "At-Tawbah", meaning: "The Repentance" },
  { number: 10, arName: "يونس", enName: "Yunus", meaning: "Jonah" },
  { number: 11, arName: "هود", enName: "Hud", meaning: "Hud" },
  { number: 12, arName: "يوسف", enName: "Yusuf", meaning: "Joseph" },
  { number: 13, arName: "الرعد", enName: "Ar-Ra'd", meaning: "The Thunder" },
  { number: 14, arName: "إبراهيم", enName: "Ibrahim", meaning: "Abraham" },
  { number: 15, arName: "الحجر", enName: "Al-Hijr", meaning: "The Rocky Tract" },
  { number: 16, arName: "النحل", enName: "An-Nahl", meaning: "The Bee" },
  { number: 17, arName: "الإسراء", enName: "Al-Isra", meaning: "The Night Journey" },
  { number: 18, arName: "الكهف", enName: "Al-Kahf", meaning: "The Cave" },
  { number: 19, arName: "مريم", enName: "Maryam", meaning: "Mary" },
  { number: 20, arName: "طه", enName: "Ta-Ha", meaning: "Ta-Ha" },
  { number: 21, arName: "الأنبياء", enName: "Al-Anbiya", meaning: "The Prophets" },
  { number: 22, arName: "الحج", enName: "Al-Hajj", meaning: "The Pilgrimage" },
  { number: 23, arName: "المؤمنون", enName: "Al-Mu'minun", meaning: "The Believers" },
  { number: 24, arName: "النور", enName: "An-Nur", meaning: "The Light" },
  { number: 25, arName: "الفرقان", enName: "Al-Furqan", meaning: "The Criterion" },
  { number: 26, arName: "الشعراء", enName: "Ash-Shu'ara", meaning: "The Poets" },
  { number: 27, arName: "النمل", enName: "An-Naml", meaning: "The Ant" },
  { number: 28, arName: "القصص", enName: "Al-Qasas", meaning: "The Stories" },
  { number: 29, arName: "العنكبوت", enName: "Al-'Ankabut", meaning: "The Spider" },
  { number: 30, arName: "الروم", enName: "Ar-Rum", meaning: "The Romans" },
  { number: 31, arName: "لقمان", enName: "Luqman", meaning: "Luqman" },
  { number: 32, arName: "السجدة", enName: "As-Sajdah", meaning: "The Prostration" },
  { number: 33, arName: "الأحزاب", enName: "Al-Ahzab", meaning: "The Combined Forces" },
  { number: 34, arName: "سبأ", enName: "Saba", meaning: "Sheba" },
  { number: 35, arName: "فاطر", enName: "Fatir", meaning: "Originator" },
  { number: 36, arName: "يس", enName: "Ya-Sin", meaning: "Ya Sin" },
  { number: 37, arName: "الصافات", enName: "As-Saffat", meaning: "Those Who Set the Ranks" },
  { number: 38, arName: "ص", enName: "Sad", meaning: "The Letter Sad" },
  { number: 39, arName: "الزمر", enName: "Az-Zumar", meaning: "The Troops" },
  { number: 40, arName: "غافر", enName: "Ghafir", meaning: "The Forgiver" },
  { number: 41, arName: "فصلت", enName: "Fussilat", meaning: "Explained in Detail" },
  { number: 42, arName: "الشورى", enName: "Ash-Shura", meaning: "The Consultation" },
  { number: 43, arName: "الزخرف", enName: "Az-Zukhruf", meaning: "The Ornaments of Gold" },
  { number: 44, arName: "الدخان", enName: "Ad-Dukhan", meaning: "The Smoke" },
  { number: 45, arName: "الجاثية", enName: "Al-Jathiyah", meaning: "The Crouching" },
  { number: 46, arName: "الأحقاف", enName: "Al-Ahqaf", meaning: "The Wind-Curved Sandhills" },
  { number: 47, arName: "محمد", enName: "Muhammad", meaning: "Muhammad" },
  { number: 48, arName: "الفتح", enName: "Al-Fath", meaning: "The Victory" },
  { number: 49, arName: "الحجرات", enName: "Al-Hujurat", meaning: "The Rooms" },
  { number: 50, arName: "ق", enName: "Qaf", meaning: "The Letter Qaf" },
  { number: 51, arName: "الذاريات", enName: "Adh-Dhariyat", meaning: "The Winnowing Winds" },
  { number: 52, arName: "الطور", enName: "At-Tur", meaning: "The Mount" },
  { number: 53, arName: "النجم", enName: "An-Najm", meaning: "The Star" },
  { number: 54, arName: "القمر", enName: "Al-Qamar", meaning: "The Moon" },
  { number: 55, arName: "الرحمن", enName: "Ar-Rahman", meaning: "The Beneficent" },
  { number: 56, arName: "الواقعة", enName: "Al-Waqi'ah", meaning: "The Inevitable" },
  { number: 57, arName: "الحديد", enName: "Al-Hadid", meaning: "The Iron" },
  { number: 58, arName: "المجادلة", enName: "Al-Mujadila", meaning: "The Pleading Woman" },
  { number: 59, arName: "الحشر", enName: "Al-Hashr", meaning: "The Exile" },
  { number: 60, arName: "الممتحنة", enName: "Al-Mumtahanah", meaning: "She That Is Examined" },
  { number: 61, arName: "الصف", enName: "As-Saf", meaning: "The Ranks" },
  { number: 62, arName: "الجمعة", enName: "Al-Jumu'ah", meaning: "Friday" },
  { number: 63, arName: "المنافقون", enName: "Al-Munafiqun", meaning: "The Hypocrites" },
  { number: 64, arName: "التغابن", enName: "At-Taghabun", meaning: "The Mutual Disillusion" },
  { number: 65, arName: "الطلاق", enName: "At-Talaq", meaning: "The Divorce" },
  { number: 66, arName: "التحريم", enName: "At-Tahrim", meaning: "The Prohibition" },
  { number: 67, arName: "الملك", enName: "Al-Mulk", meaning: "The Sovereignty" },
  { number: 68, arName: "القلم", enName: "Al-Qalam", meaning: "The Pen" },
  { number: 69, arName: "الحاقة", enName: "Al-Haqqah", meaning: "The Reality" },
  { number: 70, arName: "المعارج", enName: "Al-Ma'arij", meaning: "The Ascending Stairways" },
  { number: 71, arName: "نوح", enName: "Nuh", meaning: "Noah" },
  { number: 72, arName: "الجن", enName: "Al-Jinn", meaning: "The Jinn" },
  { number: 73, arName: "المزمل", enName: "Al-Muzzammil", meaning: "The Enshrouded One" },
  { number: 74, arName: "المدثر", enName: "Al-Muddaththir", meaning: "The Cloaked One" },
  { number: 75, arName: "القيامة", enName: "Al-Qiyamah", meaning: "The Resurrection" },
  { number: 76, arName: "الإنسان", enName: "Al-Insan", meaning: "The Man" },
  { number: 77, arName: "المرسلات", enName: "Al-Mursalat", meaning: "The Emissaries" },
  { number: 78, arName: "النبأ", enName: "An-Naba", meaning: "The Tidings" },
  { number: 79, arName: "النازعات", enName: "An-Nazi'at", meaning: "Those Who Drag Forth" },
  { number: 80, arName: "عبس", enName: "'Abasa", meaning: "He Frowned" },
  { number: 81, arName: "التكوير", enName: "At-Takwir", meaning: "The Overthrowing" },
  { number: 82, arName: "الانفطار", enName: "Al-Infitar", meaning: "The Cleaving" },
  { number: 83, arName: "المطففين", enName: "Al-Mutaffifin", meaning: "The Defrauding" },
  { number: 84, arName: "الانشقاق", enName: "Al-Inshiqaq", meaning: "The Sundering" },
  { number: 85, arName: "البروج", enName: "Al-Buruj", meaning: "The Mansions of the Stars" },
  { number: 86, arName: "الطارق", enName: "At-Tariq", meaning: "The Nightcomer" },
  { number: 87, arName: "الأعلى", enName: "Al-A'la", meaning: "The Most High" },
  { number: 88, arName: "الغاشية", enName: "Al-Ghashiyah", meaning: "The Overwhelming" },
  { number: 89, arName: "الفجر", enName: "Al-Fajr", meaning: "The Dawn" },
  { number: 90, arName: "البلد", enName: "Al-Balad", meaning: "The City" },
  { number: 91, arName: "الشمس", enName: "Ash-Shams", meaning: "The Sun" },
  { number: 92, arName: "الليل", enName: "Al-Layl", meaning: "The Night" },
  { number: 93, arName: "الضحى", enName: "Ad-Duha", meaning: "The Morning Hours" },
  { number: 94, arName: "الشرح", enName: "Ash-Sharh", meaning: "The Relief" },
  { number: 95, arName: "التين", enName: "At-Tin", meaning: "The Fig" },
  { number: 96, arName: "العلق", enName: "Al-'Alaq", meaning: "The Clot" },
  { number: 97, arName: "القدر", enName: "Al-Qadr", meaning: "The Power" },
  { number: 98, arName: "البينة", enName: "Al-Bayyinah", meaning: "The Clear Proof" },
  { number: 99, arName: "الزلزلة", enName: "Az-Zalzalah", meaning: "The Earthquake" },
  { number: 100, arName: "العاديات", enName: "Al-'Adiyat", meaning: "The Courser" },
  { number: 101, arName: "القارعة", enName: "Al-Qari'ah", meaning: "The Calamity" },
  { number: 102, arName: "التكاثر", enName: "At-Takathur", meaning: "The Rivalry in World Increase" },
  { number: 103, arName: "العصر", enName: "Al-'Asr", meaning: "The Declining Day" },
  { number: 104, arName: "الهمزة", enName: "Al-Humazah", meaning: "The Traducer" },
  { number: 105, arName: "الفيل", enName: "Al-Fil", meaning: "The Elephant" },
  { number: 106, arName: "قريش", enName: "Quraysh", meaning: "Quraysh" },
  { number: 107, arName: "الماعون", enName: "Al-Ma'un", meaning: "The Small Kindnesses" },
  { number: 108, arName: "الكوثر", enName: "Al-Kawthar", meaning: "The Abundance" },
  { number: 109, arName: "الكافرون", enName: "Al-Kafirun", meaning: "The Disbelievers" },
  { number: 110, arName: "النصر", enName: "An-Nasr", meaning: "The Divine Support" },
  { number: 111, arName: "المسد", enName: "Al-Masad", meaning: "The Palm Fiber" },
  { number: 112, arName: "الإخلاص", enName: "Al-Ikhlas", meaning: "The Sincerity" },
  { number: 113, arName: "الفلق", enName: "Al-Falaq", meaning: "The Daybreak" },
  { number: 114, arName: "الناس", enName: "An-Nas", meaning: "Mankind" }
];

export const dailyTasks = [
  "Poznaj 3 nowe litery i kliknij każdą z nich.",
  "Zrób 7 fiszek w trybie powtórek.",
  "Przećwicz wymowę słowa سلام.",
  "Narysuj literę ب na canvasie.",
  "Zagraj jedną rundę Memory Match."
];

export const asmaulHusna = [
  { n: 1, ar: "اللَّه", tr: "Allah", pl: "Bóg / Allah", en: "God / Allah", tafsir_pl: "Największe imię — obejmuje wszystkie atrybuty boskości.", tafsir_en: "The greatest name — encompassing all divine attributes." },
  { n: 2, ar: "الرَّحْمَن", tr: "Ar-Rahman", pl: "Miłosierny", en: "The Most Gracious", tafsir_pl: "Bezmiar Jego łaski obejmuje wszystkich stworzeń.", tafsir_en: "His boundless grace encompasses all of creation." },
  { n: 3, ar: "الرَّحِيم", tr: "Ar-Rahim", pl: "Miłościwy", en: "The Most Merciful", tafsir_pl: "Szczególna łaska dla wierzących w dniu ostatecznym.", tafsir_en: "Special mercy for believers on the Day of Judgment." },
  { n: 4, ar: "الْمَلِك", tr: "Al-Malik", pl: "Władca", en: "The Sovereign", tafsir_pl: "Absolutny król wszechświata, bez współwładcy.", tafsir_en: "The absolute king of the universe, with no partner." },
  { n: 5, ar: "الْقُدُّوس", tr: "Al-Quddus", pl: "Święty", en: "The Holy", tafsir_pl: "Wolny od wszelkich niedoskonałości i braków.", tafsir_en: "Free from all imperfections and deficiencies." },
  { n: 6, ar: "السَّلَام", tr: "As-Salam", pl: "Źródło Pokoju", en: "The Source of Peace", tafsir_pl: "Daje pokój stworzeniu i jest wolny od wszelkiego zła.", tafsir_en: "Grants peace and is free from all harm." },
  { n: 7, ar: "الْمُؤْمِن", tr: "Al-Mu'min", pl: "Dawca Bezpieczeństwa", en: "The Inspirer of Faith", tafsir_pl: "Zapewnia bezpieczeństwo wierzącym i potwierdza prawdę.", tafsir_en: "Grants security to believers and confirms the truth." },
  { n: 8, ar: "الْمُهَيْمِن", tr: "Al-Muhaymin", pl: "Czuwający", en: "The Guardian", tafsir_pl: "Czuwa nad wszystkim i zarządza wszystkim.", tafsir_en: "Watches over all things and governs everything." },
  { n: 9, ar: "الْعَزِيز", tr: "Al-'Aziz", pl: "Wszechmocny", en: "The Almighty", tafsir_pl: "Niezwyciężony, potężny i godnościowy.", tafsir_en: "Invincible, powerful and dignified." },
  { n: 10, ar: "الْجَبَّار", tr: "Al-Jabbar", pl: "Naprawiający złamane", en: "The Compeller", tafsir_pl: "Naprawia złamane serca i zmusza do sprawiedliwości.", tafsir_en: "Mends broken hearts and compels toward justice." },
  { n: 11, ar: "الْمُتَكَبِّر", tr: "Al-Mutakabbir", pl: "Majestatyczny", en: "The Supreme", tafsir_pl: "Jedyny godzien najwyższego majestatu.", tafsir_en: "The only one deserving supreme majesty." },
  { n: 12, ar: "الْخَالِق", tr: "Al-Khaliq", pl: "Stwórca", en: "The Creator", tafsir_pl: "Stwarza wszystko z niczego.", tafsir_en: "Creates everything from nothing." },
  { n: 13, ar: "الْبَارِئ", tr: "Al-Bari'", pl: "Twórca form", en: "The Evolver", tafsir_pl: "Tworzy stworzenia w precyzyjnych, odrębnych formach.", tafsir_en: "Creates beings in precise, distinct forms." },
  { n: 14, ar: "الْمُصَوِّر", tr: "Al-Musawwir", pl: "Nadający kształty", en: "The Fashioner", tafsir_pl: "Nadaje każdemu stworzeniu unikalny kształt.", tafsir_en: "Gives each creation its unique form." },
  { n: 15, ar: "الْغَفَّار", tr: "Al-Ghaffar", pl: "Wielce Wybaczający", en: "The Ever-Forgiving", tafsir_pl: "Przebacza grzechy wciąż na nowo.", tafsir_en: "Forgives sins again and again." },
  { n: 16, ar: "الْقَهَّار", tr: "Al-Qahhar", pl: "Poskramiający", en: "The Subduer", tafsir_pl: "Pokonuje i poskramia wszystko co mu przeciwne.", tafsir_en: "Overcomes and subdues all that opposes Him." },
  { n: 17, ar: "الْوَهَّاب", tr: "Al-Wahhab", pl: "Hojny Darczyńca", en: "The Bestower", tafsir_pl: "Daje dary bez oczekiwania czegokolwiek w zamian.", tafsir_en: "Gives gifts without expecting anything in return." },
  { n: 18, ar: "الرَّزَّاق", tr: "Ar-Razzaq", pl: "Żywiciel", en: "The Provider", tafsir_pl: "Zapewnia pożywienie wszystkim stworzeniom.", tafsir_en: "Provides sustenance for all of creation." },
  { n: 19, ar: "الْفَتَّاح", tr: "Al-Fattah", pl: "Otwierający", en: "The Opener", tafsir_pl: "Otwiera drzwi łaski i wiedzy.", tafsir_en: "Opens the doors of mercy and knowledge." },
  { n: 20, ar: "الْعَلِيم", tr: "Al-'Alim", pl: "Wszechwiedzący", en: "The All-Knowing", tafsir_pl: "Jego wiedza obejmuje wszystko — jawne i ukryte.", tafsir_en: "His knowledge encompasses everything — seen and unseen." },
  { n: 21, ar: "الْقَابِض", tr: "Al-Qabid", pl: "Ograniczający", en: "The Constrictor", tafsir_pl: "Zatrzymuje i ogranicza według swojej mądrości.", tafsir_en: "Withholds and restricts according to His wisdom." },
  { n: 22, ar: "الْبَاسِط", tr: "Al-Basit", pl: "Rozszerzający", en: "The Extender", tafsir_pl: "Rozszerza zaopatrzenie i łaskę.", tafsir_en: "Expands provision and grace." },
  { n: 23, ar: "الْخَافِض", tr: "Al-Khafid", pl: "Poniżający tyranów", en: "The Abaser", tafsir_pl: "Poniża tych którzy się buntują przeciw Bogu.", tafsir_en: "Humbles those who transgress against God." },
  { n: 24, ar: "الرَّافِع", tr: "Ar-Rafi'", pl: "Wywyższający", en: "The Exalter", tafsir_pl: "Wywyższa tych którym zechce.", tafsir_en: "Raises up those whom He wills." },
  { n: 25, ar: "الْمُعِزّ", tr: "Al-Mu'izz", pl: "Honorujący", en: "The Bestower of Honour", tafsir_pl: "Obdarza honorem i godnością.", tafsir_en: "Grants honour and dignity." },
  { n: 26, ar: "الْمُذِلّ", tr: "Al-Mudhill", pl: "Upokarzający pysznych", en: "The Humiliator", tafsir_pl: "Upokarza pysznych i niesprawiedliwych.", tafsir_en: "Humiliates the arrogant and unjust." },
  { n: 27, ar: "السَّمِيع", tr: "As-Sami'", pl: "Wszechsłyszący", en: "The All-Hearing", tafsir_pl: "Słyszy każde słowo i każdą myśl.", tafsir_en: "Hears every word and every thought." },
  { n: 28, ar: "الْبَصِير", tr: "Al-Basir", pl: "Wszechwidzący", en: "The All-Seeing", tafsir_pl: "Widzi każdy atom w stworzeniu.", tafsir_en: "Sees every atom in creation." },
  { n: 29, ar: "الْحَكَم", tr: "Al-Hakam", pl: "Sędzia", en: "The Judge", tafsir_pl: "Ostateczny sędzia wszystkich spraw.", tafsir_en: "The ultimate judge of all matters." },
  { n: 30, ar: "الْعَدْل", tr: "Al-'Adl", pl: "Sprawiedliwy", en: "The Just", tafsir_pl: "Absolutna sprawiedliwość — nie skrzywdzi nikogo.", tafsir_en: "Absolute justice — will wrong no one." },
  { n: 31, ar: "اللَّطِيف", tr: "Al-Latif", pl: "Subtelny i Łaskawy", en: "The Subtle One", tafsir_pl: "Wie o najsubtelniejszych sprawach i jest łaskawy.", tafsir_en: "Knows the most subtle matters and is kind." },
  { n: 32, ar: "الْخَبِير", tr: "Al-Khabir", pl: "Świadomy wszystkiego", en: "The All-Aware", tafsir_pl: "Świadom wszelkich wewnętrznych stanów i spraw.", tafsir_en: "Aware of all inner states and affairs." },
  { n: 33, ar: "الْحَلِيم", tr: "Al-Halim", pl: "Wyrozumiały", en: "The Forbearing", tafsir_pl: "Nie spieszy się z karą lecz daje czas na skruchę.", tafsir_en: "Does not rush to punish but gives time to repent." },
  { n: 34, ar: "الْعَظِيم", tr: "Al-'Azim", pl: "Wspaniały", en: "The Magnificent", tafsir_pl: "Jego wielkość przekracza wszelkie wyobrażenie.", tafsir_en: "His greatness surpasses all imagination." },
  { n: 35, ar: "الْغَفُور", tr: "Al-Ghafur", pl: "Wszechprzebaczający", en: "The All-Forgiving", tafsir_pl: "Przebacza nawet największe grzechy.", tafsir_en: "Forgives even the greatest sins." },
  { n: 36, ar: "الشَّكُور", tr: "Ash-Shakur", pl: "Doceniający", en: "The Appreciative", tafsir_pl: "Nagradza nawet najmniejsze dobre czyny.", tafsir_en: "Rewards even the smallest good deeds." },
  { n: 37, ar: "الْعَلِيّ", tr: "Al-'Ali", pl: "Najwyższy", en: "The Most High", tafsir_pl: "Wyniesiony ponad wszystko stworzenie.", tafsir_en: "Elevated above all of creation." },
  { n: 38, ar: "الْكَبِير", tr: "Al-Kabir", pl: "Największy", en: "The Greatest", tafsir_pl: "Nieporównywalnie większy od wszystkiego.", tafsir_en: "Incomparably greater than everything." },
  { n: 39, ar: "الْحَفِيظ", tr: "Al-Hafiz", pl: "Stróż", en: "The Preserver", tafsir_pl: "Zachowuje i strzeże wszystkiego.", tafsir_en: "Preserves and guards all things." },
  { n: 40, ar: "الْمُقِيت", tr: "Al-Muqit", pl: "Podtrzymujący życie", en: "The Nourisher", tafsir_pl: "Podtrzymuje życie każdego stworzenia.", tafsir_en: "Sustains the life of every creature." },
  { n: 41, ar: "الْحَسِيب", tr: "Al-Hasib", pl: "Obliczający", en: "The Reckoner", tafsir_pl: "Rozlicza wszystkie czyny z najwyższą precyzją.", tafsir_en: "Accounts for all deeds with supreme precision." },
  { n: 42, ar: "الْجَلِيل", tr: "Al-Jalil", pl: "Majestatyczny", en: "The Majestic", tafsir_pl: "Posiadający absolutny majestat i chwałę.", tafsir_en: "Possessing absolute majesty and glory." },
  { n: 43, ar: "الْكَرِيم", tr: "Al-Karim", pl: "Hojny", en: "The Generous", tafsir_pl: "Hojność bez granic — daje nawet tym którzy Go nie proszą.", tafsir_en: "Boundless generosity — gives even to those who don't ask." },
  { n: 44, ar: "الرَّقِيب", tr: "Ar-Raqib", pl: "Czuwający nad wszystkim", en: "The Watchful", tafsir_pl: "Obserwuje każdy czyn każdego stworzenia.", tafsir_en: "Observes every deed of every creature." },
  { n: 45, ar: "الْمُجِيب", tr: "Al-Mujib", pl: "Odpowiadający na modlitwy", en: "The Responsive", tafsir_pl: "Odpowiada na każdą szczerą prośbę.", tafsir_en: "Responds to every sincere supplication." },
  { n: 46, ar: "الْوَاسِع", tr: "Al-Wasi'", pl: "Nieograniczony", en: "The All-Encompassing", tafsir_pl: "Jego łaska i wiedza nie mają granic.", tafsir_en: "His mercy and knowledge have no limits." },
  { n: 47, ar: "الْحَكِيم", tr: "Al-Hakim", pl: "Mądry", en: "The All-Wise", tafsir_pl: "Każda Jego decyzja jest mądra i celowa.", tafsir_en: "Every His decision is wise and purposeful." },
  { n: 48, ar: "الْوَدُود", tr: "Al-Wadud", pl: "Kochający", en: "The Loving", tafsir_pl: "Kocha tych którzy czynią dobro.", tafsir_en: "Loves those who do good." },
  { n: 49, ar: "الْمَجِيد", tr: "Al-Majid", pl: "Chwałorodny", en: "The Most Glorious", tafsir_pl: "Niezrównana chwała i szlachetność.", tafsir_en: "Unmatched glory and nobility." },
  { n: 50, ar: "الْبَاعِث", tr: "Al-Ba'ith", pl: "Wskrzeszający", en: "The Resurrector", tafsir_pl: "Wskrzesi wszystkich w dniu ostatecznym.", tafsir_en: "Will resurrect all on the Last Day." },
  { n: 51, ar: "الشَّهِيد", tr: "Ash-Shahid", pl: "Świadek", en: "The Witness", tafsir_pl: "Świadkiem każdej chwili i każdego miejsca.", tafsir_en: "Witness to every moment and every place." },
  { n: 52, ar: "الْحَقّ", tr: "Al-Haqq", pl: "Prawda absolutna", en: "The Truth", tafsir_pl: "Jedyna absolutna prawda — wszystko inne jest względne.", tafsir_en: "The only absolute truth — everything else is relative." },
  { n: 53, ar: "الْوَكِيل", tr: "Al-Wakil", pl: "Powiernik", en: "The Trustee", tafsir_pl: "Wystarczy powierzyć Mu wszystkie sprawy.", tafsir_en: "Sufficient to entrust all affairs to Him." },
  { n: 54, ar: "الْقَوِيّ", tr: "Al-Qawi", pl: "Silny", en: "The All-Strong", tafsir_pl: "Jego siła jest absolutna i nieograniczona.", tafsir_en: "His strength is absolute and unlimited." },
  { n: 55, ar: "الْمَتِين", tr: "Al-Matin", pl: "Nieugięty", en: "The Firm", tafsir_pl: "Jego siła i postanowienia są niepokonane.", tafsir_en: "His strength and decrees are indomitable." },
  { n: 56, ar: "الْوَلِيّ", tr: "Al-Wali", pl: "Opiekun wierzących", en: "The Protecting Friend", tafsir_pl: "Przyjaciel i opiekun wierzących.", tafsir_en: "Friend and protector of the believers." },
  { n: 57, ar: "الْحَمِيد", tr: "Al-Hamid", pl: "Godny wszelkiej chwały", en: "The Praiseworthy", tafsir_pl: "Godny wszelkiej chwały i wdzięczności.", tafsir_en: "Worthy of all praise and gratitude." },
  { n: 58, ar: "الْمُحْصِي", tr: "Al-Muhsi", pl: "Zliczający wszystko", en: "The Counter", tafsir_pl: "Zlicza każdy atom i każdy czyn.", tafsir_en: "Counts every atom and every deed." },
  { n: 59, ar: "الْمُبْدِئ", tr: "Al-Mubdi'", pl: "Inicjujący stworzenie", en: "The Originator", tafsir_pl: "Zaczyna stworzenie bez precedensu.", tafsir_en: "Begins creation without precedent." },
  { n: 60, ar: "الْمُعِيد", tr: "Al-Mu'id", pl: "Przywracający do życia", en: "The Restorer", tafsir_pl: "Przywróci stworzenie po jego śmierci.", tafsir_en: "Will restore creation after its death." },
  { n: 61, ar: "الْمُحْيِي", tr: "Al-Muhyi", pl: "Ożywiający", en: "The Giver of Life", tafsir_pl: "Daje życie wszystkiemu co żywe.", tafsir_en: "Gives life to all that lives." },
  { n: 62, ar: "الْمُمِيت", tr: "Al-Mumit", pl: "Dający śmierć", en: "The Bringer of Death", tafsir_pl: "Śmierć jest Jego dziełem — nie ma od niej ucieczki.", tafsir_en: "Death is His work — there is no escape from it." },
  { n: 63, ar: "الْحَيّ", tr: "Al-Hayy", pl: "Wiecznie Żyjący", en: "The Ever Living", tafsir_pl: "Żyje wiecznie — nie zazna śmierci.", tafsir_en: "Lives eternally — will never experience death." },
  { n: 64, ar: "الْقَيُّوم", tr: "Al-Qayyum", pl: "Samoistny Podtrzymujący", en: "The Sustainer", tafsir_pl: "Samoistny i podtrzymuje cały wszechświat.", tafsir_en: "Self-sustaining and maintains the entire universe." },
  { n: 65, ar: "الْوَاجِد", tr: "Al-Wajid", pl: "Wszystko posiadający", en: "The Finder", tafsir_pl: "Wszystko jest dla Niego dostępne.", tafsir_en: "Everything is available to Him." },
  { n: 66, ar: "الْمَاجِد", tr: "Al-Majid", pl: "Szlachetny", en: "The Glorious", tafsir_pl: "Szlachetny w swoich atrybutach i działaniach.", tafsir_en: "Noble in His attributes and actions." },
  { n: 67, ar: "الْوَاحِد", tr: "Al-Wahid", pl: "Jedyny", en: "The One", tafsir_pl: "Jedyny bez żadnego partnera czy równego.", tafsir_en: "The One with no partner or equal." },
  { n: 68, ar: "الْأَحَد", tr: "Al-Ahad", pl: "Absolutnie Jedyny", en: "The Unique", tafsir_pl: "Absolutnie jedyny — Jego jedność jest niepodzielna.", tafsir_en: "Absolutely one — His oneness is indivisible." },
  { n: 69, ar: "الصَّمَد", tr: "As-Samad", pl: "Samowystarczalny", en: "The Eternal", tafsir_pl: "Wszystko Go potrzebuje, On niczego.", tafsir_en: "All need Him, He needs nothing." },
  { n: 70, ar: "الْقَادِر", tr: "Al-Qadir", pl: "Wszechwładny", en: "The All-Powerful", tafsir_pl: "Zdolny do wszystkiego co tylko zechce.", tafsir_en: "Capable of all that He wills." },
  { n: 71, ar: "الْمُقْتَدِر", tr: "Al-Muqtadir", pl: "Wykonujący swoją wolę", en: "The All-Determining", tafsir_pl: "Wykonuje swoją wolę z absolutną mocą.", tafsir_en: "Executes His will with absolute power." },
  { n: 72, ar: "الْمُقَدِّم", tr: "Al-Muqaddim", pl: "Przyspieszający", en: "The Expediter", tafsir_pl: "Stawia rzeczy na pierwszym miejscu według mądrości.", tafsir_en: "Places things first according to His wisdom." },
  { n: 73, ar: "الْمُؤَخِّر", tr: "Al-Mu'akhkhir", pl: "Opóźniający", en: "The Delayer", tafsir_pl: "Opóźnia według Swojej mądrości i planu.", tafsir_en: "Delays according to His wisdom and plan." },
  { n: 74, ar: "الْأَوَّل", tr: "Al-Awwal", pl: "Pierwszy", en: "The First", tafsir_pl: "Był zanim cokolwiek istniało.", tafsir_en: "Existed before anything else existed." },
  { n: 75, ar: "الْآخِر", tr: "Al-Akhir", pl: "Ostatni", en: "The Last", tafsir_pl: "Pozostanie po tym jak wszystko przeminie.", tafsir_en: "Will remain after everything else has perished." },
  { n: 76, ar: "الظَّاهِر", tr: "Az-Zahir", pl: "Jawny przez znaki", en: "The Manifest", tafsir_pl: "Objawia się przez znaki w stworzeniu.", tafsir_en: "Manifests through signs in creation." },
  { n: 77, ar: "الْبَاطِن", tr: "Al-Batin", pl: "Ukryty", en: "The Hidden", tafsir_pl: "Ukryty przed wzrokiem lecz bliższy niż żyła szyjna.", tafsir_en: "Hidden from sight yet closer than the jugular vein." },
  { n: 78, ar: "الْوَالِي", tr: "Al-Wali", pl: "Zarządca", en: "The Governor", tafsir_pl: "Zarządza wszystkimi sprawami stworzenia.", tafsir_en: "Governs all affairs of creation." },
  { n: 79, ar: "الْمُتَعَالِ", tr: "Al-Muta'ali", pl: "Wzniosły", en: "The Self-Exalted", tafsir_pl: "Wznosi się ponad wszelkie opisy i ograniczenia.", tafsir_en: "Rises above all descriptions and limitations." },
  { n: 80, ar: "الْبَرّ", tr: "Al-Barr", pl: "Dobrotliwy", en: "The Most Kind", tafsir_pl: "Dobry dla stworzenia — łaskawy i hojny.", tafsir_en: "Kind to creation — gracious and generous." },
  { n: 81, ar: "التَّوَّاب", tr: "At-Tawwab", pl: "Przyjmujący skruchę", en: "The Acceptor of Repentance", tafsir_pl: "Przyjmuje pokutę wciąż na nowo z miłością.", tafsir_en: "Accepts repentance again and again with love." },
  { n: 82, ar: "الْمُنْتَقِم", tr: "Al-Muntaqim", pl: "Mszczący uciśnionych", en: "The Avenger", tafsir_pl: "Pomści uciśnionych i ukarze tyranów.", tafsir_en: "Will avenge the oppressed and punish tyrants." },
  { n: 83, ar: "الْعَفُوّ", tr: "Al-'Afuww", pl: "Wymazujący grzechy", en: "The Pardoner", tafsir_pl: "Wymazuje grzechy zupełnie — jakby ich nie było.", tafsir_en: "Erases sins completely — as if they never were." },
  { n: 84, ar: "الرَّؤُوف", tr: "Ar-Ra'uf", pl: "Niezwykle Czuły", en: "The Compassionate", tafsir_pl: "Niezwykle czuły i współczujący wobec stworzenia.", tafsir_en: "Extremely tender and compassionate toward creation." },
  { n: 85, ar: "مَالِكُ الْمُلْك", tr: "Malik al-Mulk", pl: "Władca Królestwa", en: "The Owner of Sovereignty", tafsir_pl: "Jedyny prawowity władca całego stworzenia.", tafsir_en: "The only rightful ruler of all creation." },
  { n: 86, ar: "ذُو الْجَلَالِ وَالْإِكْرَام", tr: "Dhu l-Jalali wa-l-Ikram", pl: "Pan Majestatu i Łaski", en: "The Lord of Majesty and Bounty", tafsir_pl: "Łączy majestat z łaską — potęgę z dobrocią.", tafsir_en: "Combines majesty with grace — power with goodness." },
  { n: 87, ar: "الْمُقْسِط", tr: "Al-Muqsit", pl: "Bezstronny", en: "The Equitable", tafsir_pl: "Równy i sprawiedliwy wobec wszystkich.", tafsir_en: "Fair and just to all without exception." },
  { n: 88, ar: "الْجَامِع", tr: "Al-Jami'", pl: "Gromadzący wszystkich", en: "The Gatherer", tafsir_pl: "Zgromadzi wszystkich w dniu ostatecznym.", tafsir_en: "Will gather everyone on the Last Day." },
  { n: 89, ar: "الْغَنِيّ", tr: "Al-Ghani", pl: "Samowystarczalny", en: "The All-Sufficient", tafsir_pl: "Nie potrzebuje niczego — jest absolutnie samowystarczalny.", tafsir_en: "Needs nothing — absolutely self-sufficient." },
  { n: 90, ar: "الْمُغْنِي", tr: "Al-Mughni", pl: "Wzbogacający", en: "The Enricher", tafsir_pl: "Wzbogaca kogo chce — materialnie i duchowo.", tafsir_en: "Enriches whom He wills — materially and spiritually." },
  { n: 91, ar: "الْمَانِع", tr: "Al-Mani'", pl: "Powstrzymujący zło", en: "The Preventer", tafsir_pl: "Powstrzymuje zło i chroni od szkody.", tafsir_en: "Prevents harm and protects from evil." },
  { n: 92, ar: "الضَّارّ", tr: "Ad-Darr", pl: "Dopuszczający próby", en: "The Distresser", tafsir_pl: "Dopuszcza próby dla mądrości i oczyszczenia.", tafsir_en: "Permits trials for wisdom and purification." },
  { n: 93, ar: "النَّافِع", tr: "An-Nafi'", pl: "Zsyłający dobro", en: "The Benefiter", tafsir_pl: "Zsyła dobro i korzyści dla stworzenia.", tafsir_en: "Sends good and benefits to creation." },
  { n: 94, ar: "النُّور", tr: "An-Nur", pl: "Światło", en: "The Light", tafsir_pl: "Oświetla niebiosa i ziemię Swoim światłem (24:35).", tafsir_en: "Illuminates the heavens and earth with His light (24:35)." },
  { n: 95, ar: "الْهَادِي", tr: "Al-Hadi", pl: "Przewodnik na prostą drogę", en: "The Guide", tafsir_pl: "Prowadzi ku prawdzie tych którzy szukają.", tafsir_en: "Guides to truth those who seek it." },
  { n: 96, ar: "الْبَدِيع", tr: "Al-Badi'", pl: "Stwórca doskonałości", en: "The Incomparable", tafsir_pl: "Tworzy rzeczy doskonałe bez wzoru ani podobieństwa.", tafsir_en: "Creates perfect things without model or likeness." },
  { n: 97, ar: "الْبَاقِي", tr: "Al-Baqi", pl: "Wiecznotrwały", en: "The Everlasting", tafsir_pl: "Trwa wiecznie — bez początku i bez końca.", tafsir_en: "Lasts forever — without beginning or end." },
  { n: 98, ar: "الْوَارِث", tr: "Al-Warith", pl: "Dziedzic wszechświata", en: "The Inheritor", tafsir_pl: "Dziedziczy wszystko gdy wszechświat przeminie.", tafsir_en: "Inherits everything when the universe perishes." },
  { n: 99, ar: "الرَّشِيد", tr: "Ar-Rashid", pl: "Prowadzący prostą drogą", en: "The Guide to Right Path", tafsir_pl: "Prowadzi swoich wiernych na prostą drogę.", tafsir_en: "Leads His faithful on the straight path." }
];

export const islamicHadith = [
  { id: 1, ar: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ", tr: "Innama al-a'malu bin-niyyat", pl: "Czyny ocenia się według intencji.", en: "Actions are judged by intentions.", source: "Bukhari 1" },
  { id: 2, ar: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ", tr: "Al-Muslimu man salimal-Muslimuna min lisanihi wa-yadihi", pl: "Muzułmanin to ten, od którego języka i rąk bezpieczni są inni.", en: "A Muslim is the one from whose tongue and hands others are safe.", source: "Bukhari 10" },
  { id: 3, ar: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ", tr: "Khayrukum man ta'allamal-Qur'ana wa 'allamah", pl: "Najlepszym z was jest ten, kto uczy się Koranu i naucza go innych.", en: "The best among you is the one who learns the Quran and teaches it.", source: "Bukhari 5027" },
  { id: 4, ar: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ", tr: "Talabul-'ilmi faridatun 'ala kulli Muslim", pl: "Poszukiwanie wiedzy jest obowiązkiem każdego muzułmanina.", en: "Seeking knowledge is an obligation upon every Muslim.", source: "Ibn Majah 224" },
  { id: 5, ar: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", tr: "La yu'minu ahadukum hatta yuhibba li-akhihi ma yuhibbu li-nafsih", pl: "Nikt z was nie jest prawdziwym wierzącym, dopóki nie kocha dla swego brata tego, co kocha dla siebie.", en: "None of you truly believes until he loves for his brother what he loves for himself.", source: "Bukhari 13" },
  { id: 6, ar: "الدِّينُ النَّصِيحَةُ", tr: "Ad-dinu an-nasiha", pl: "Religia to szczera dobroć.", en: "The religion is sincere advice.", source: "Muslim 55" },
  { id: 7, ar: "الصَّوْمُ جُنَّةٌ", tr: "As-sawmu junna", pl: "Post jest tarczą.", en: "Fasting is a shield.", source: "Bukhari 1894" },
  { id: 8, ar: "كُلُّ مَعْرُوفٍ صَدَقَةٌ", tr: "Kullu ma'rufin sadaqa", pl: "Każdy dobry czyn jest jałmużną.", en: "Every act of kindness is charity.", source: "Bukhari 6021" },
  { id: 9, ar: "الْجَنَّةُ تَحْتَ أَقْدَامِ الْأُمَّهَاتِ", tr: "Al-jannatu tahta aqdamil-ummahat", pl: "Raj jest pod stopami matek.", en: "Paradise lies at the feet of mothers.", source: "Nasai 3104" },
  { id: 10, ar: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ", tr: "Khayrun-nasi anfa'uhum lin-nas", pl: "Najlepszy z ludzi to ten, kto jest najbardziej pożyteczny dla innych.", en: "The best of people are those most beneficial to others.", source: "Tabarani" },
  { id: 11, ar: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ صَدَقَةٌ", tr: "Tabassmuka fi wajhi akhika sadaqa", pl: "Uśmiech w twarz swego brata jest jałmużną.", en: "Your smile at your brother's face is charity.", source: "Tirmidhi 1956" },
  { id: 12, ar: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ", tr: "Man kana yu'minu billahi wal-yawmil-akhiri falyaqul khayran aw liyasmut", pl: "Kto wierzy w Allaha i Dzień Ostatni — niech mówi dobro albo niech milczy.", en: "Whoever believes in Allah and the Last Day should speak good or remain silent.", source: "Bukhari 6018" },
  { id: 13, ar: "إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ", tr: "Innallaha jamilun yuhibbul-jamal", pl: "Zaprawdę Allah jest piękny i kocha piękno.", en: "Indeed Allah is beautiful and loves beauty.", source: "Muslim 91" },
  { id: 14, ar: "أَكْمَلُ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا", tr: "Akmalul-mu'minina imanan ahsanuhum khuluqa", pl: "Wierzący o najpełniejszej wierze to ten, kto ma najlepszy charakter.", en: "The most complete believer is the one with the best character.", source: "Abu Dawud 4682" },
  { id: 15, ar: "مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ", tr: "Ma naqasat sadaqatun min mal", pl: "Jałmużna nie zmniejszy majątku.", en: "Charity does not decrease wealth.", source: "Muslim 2588" },
  { id: 16, ar: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ", tr: "Ar-rahimuna yarhamuhum ar-Rahman", pl: "Miłosiernych obdarza miłosierdziem Miłosierny.", en: "The merciful are shown mercy by the All-Merciful.", source: "Abu Dawud 4941" },
  { id: 17, ar: "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا", tr: "Ittaqillaha haythuma kunta wa-atbi'is-sayyi'atal-hasanata tamhuha", pl: "Bój się Allaha gdziekolwiek jesteś, po złym czynie uczyń dobry — wymaże go.", en: "Fear Allah wherever you are; follow a bad deed with a good one and it will wipe it out.", source: "Tirmidhi 1987" },
  { id: 18, ar: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ", tr: "Man salaka tariqan yaltamisu fihi 'ilman sahhallahu lahu tariqan ilal-janna", pl: "Kto chodzi drogą w poszukiwaniu wiedzy, Allah ułatwi mu drogę do raju.", en: "Whoever takes a path seeking knowledge, Allah makes easy for him a path to Paradise.", source: "Muslim 2699" },
  { id: 19, ar: "كُنْ فِي الدُّنْيَا كَأَنَّكَ غَرِيبٌ أَوْ عَابِرُ سَبِيلٍ", tr: "Kun fid-dunya ka-annaka gharibun aw 'abiru sabil", pl: "Bądź na tym świecie jak obcy lub podróżnik.", en: "Be in this world as if you were a stranger or a traveler.", source: "Bukhari 6416" },
  { id: 20, ar: "مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ", tr: "Man yuridillahu bihi khayran yufaqqihhu fid-din", pl: "Komu Allah życzy dobra, temu daje rozumienie religii.", en: "Whoever Allah wants good for, He gives them understanding of the religion.", source: "Bukhari 71" },
  { id: 21, ar: "إِذَا مَاتَ ابْنُ آدَمَ انْقَطَعَ عَنْهُ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ", tr: "Idha mata ibnu adama inqata'a 'anhu 'amaluhu illa min thalatha", pl: "Gdy umrze człowiek, odcina się od niego czyn — poza trzema: sadaqa jariyya, wiedza z której korzystają, pobożne dziecko które się modli.", en: "When a person dies, all deeds end except three: ongoing charity, beneficial knowledge, or a righteous child who prays for them.", source: "Muslim 1631" },
  { id: 22, ar: "إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ", tr: "Innallaha la yanzuru ila suwarikum wa-amwalikum wa-lakin yanzuru ila qulubikum", pl: "Allah nie patrzy na wasze twarze ani majątki, lecz patrzy na wasze serca.", en: "Allah does not look at your faces or wealth, but looks at your hearts.", source: "Muslim 2564" },
  { id: 23, ar: "الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا", tr: "Al-mu'minu lil-mu'mini kal-bunyanil yashuddu ba'duhu ba'da", pl: "Wierzący wobec wierzącego jest jak budynek — jedne części wzmacniają drugie.", en: "A believer to another believer is like a building — each part strengthens the other.", source: "Bukhari 481" },
  { id: 24, ar: "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ", tr: "Laysa ash-shadidu bis-sur'ati innama ash-shadidu alladhi yamliku nafsahu 'indal-ghadab", pl: "Silny to nie ten, kto pokonuje innych — silny to ten, kto panuje nad sobą w gniewie.", en: "The strong man is not the one who overpowers others — the strong man controls himself when angry.", source: "Bukhari 6114" },
  { id: 25, ar: "مَنْ أَحَبَّ لِقَاءَ اللَّهِ أَحَبَّ اللَّهُ لِقَاءَهُ", tr: "Man ahabba liqa'allahi ahabballahu liqa'ah", pl: "Kto pragnie spotkania z Allahem, Allah pragnie spotkania z nim.", en: "Whoever loves to meet Allah, Allah loves to meet him.", source: "Bukhari 6507" },
  { id: 26, ar: "خَيْرُ الصَّدَقَةِ مَا كَانَ عَنْ ظَهْرِ غِنًى", tr: "Khayrus-sadaqati ma kana 'an zahri ghina", pl: "Najlepsza jałmużna to ta, która pochodzi z dostatku.", en: "The best charity is that given from a position of sufficiency.", source: "Bukhari 1426" },
  { id: 27, ar: "الْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى", tr: "Al-yadul-'ulya khayrun minal-yadis-sufla", pl: "Ręka dająca jest lepsza od ręki biorącej.", en: "The upper hand is better than the lower hand.", source: "Bukhari 1429" },
  { id: 28, ar: "بَشِّرُوا وَلَا تُنَفِّرُوا وَيَسِّرُوا وَلَا تُعَسِّرُوا", tr: "Bashshiru wa-la tunaffiru wa-yassiru wa-la tu'assiru", pl: "Głoście dobrą nowinę i nie odstraszajcie, ułatwiajcie i nie utrudniajcie.", en: "Give glad tidings and do not drive people away; make things easy and not difficult.", source: "Bukhari 69" },
  { id: 29, ar: "إِنَّ مِنَ الشِّعْرِ حِكْمَةً", tr: "Inna minash-shi'ri hikmah", pl: "Zaprawdę w poezji jest mądrość.", en: "Indeed, some poetry contains wisdom.", source: "Bukhari 6145" },
  { id: 30, ar: "حُبُّكَ الشَّيْءَ يُعْمِي وَيُصِمُّ", tr: "Hubbuka sh-shay'a yu'mi wa-yusimm", pl: "Miłość do czegoś czyni ślepym i głuchym.", en: "Your love for something blinds and deafens.", source: "Abu Dawud 5130" }
];

export const seerahTimeline = [
  { year: "570 n.e.", hijri: "Rok Słonia", pl: "Narodziny Proroka Muhammada ﷺ", en: "Birth of Prophet Muhammad ﷺ", desc_pl: "Urodzony w Mekce w plemieniu Quraysh. Ojciec Abdullah zmarł przed narodzinami.", desc_en: "Born in Mecca in the Quraysh tribe. Father Abdullah died before his birth." },
  { year: "610 n.e.", hijri: "1. rok objawienia", pl: "Pierwsze Objawienie w jaskini Hira", en: "First Revelation in Cave Hira", desc_pl: "Anioł Dżibril objawił pierwsze wersety sury Al-Alaq: 'Czytaj w imię Pana...'. Prorok miał 40 lat.", desc_en: "Angel Jibreel revealed the first verses of Al-Alaq: 'Read in the name of your Lord...' The Prophet was 40 years old." },
  { year: "613 n.e.", hijri: "3 lata po objawieniu", pl: "Publiczne głoszenie islamu", en: "Public Proclamation of Islam", desc_pl: "Prorok ﷺ zaczął publicznie głosić nową religię. Zaczęły się prześladowania pierwszych muzułmanów.", desc_en: "The Prophet ﷺ began publicly preaching. Persecution of early Muslims began." },
  { year: "619 n.e.", hijri: "Rok Smutku", pl: "Rok Smutku — śmierć Chadidży i Abu Taliba", en: "Year of Grief — death of Khadijah and Abu Talib", desc_pl: "W jednym roku umarły dwie osoby które go chroniły: ukochana żona Chadidża i wuj Abu Talib.", desc_en: "In one year died the two people who protected him: beloved wife Khadijah and uncle Abu Talib." },
  { year: "620 n.e.", hijri: "ok. 10 roku misji", pl: "Isra wal-Mi'radż — Nocna podróż", en: "Isra wal-Mi'raj — Night Journey", desc_pl: "Nocna podróż do Jerozolimy i wstąpienie przez 7 sfer niebieskich do Allaha. Ustanowiono 5 modlitw.", desc_en: "Night journey to Jerusalem and ascension through 7 heavens to Allah. The 5 daily prayers were established." },
  { year: "622 n.e.", hijri: "1 AH", pl: "Hidżra — migracja do Medyny", en: "Hijra — Migration to Madinah", desc_pl: "Prorok ﷺ i muzułmanie migrowali do Medyny. Rok ten stał się początkiem kalendarza muzułmańskiego.", desc_en: "The Prophet ﷺ and Muslims migrated to Madinah. This became the start of the Islamic calendar." },
  { year: "624 n.e.", hijri: "2 AH", pl: "Bitwa pod Badr", en: "Battle of Badr", desc_pl: "313 muzułmanów pokonało armię 1000 Mecczyczyków. Wielkie zwycięstwo opisane w Koranie.", desc_en: "313 Muslims defeated an army of 1000 Meccans. A great victory described in the Quran." },
  { year: "625 n.e.", hijri: "3 AH", pl: "Bitwa pod Uhud", en: "Battle of Uhud", desc_pl: "Muzułmanie ponieśli straty gdy łucznicy opuścili stanowiska. Prorok ﷺ był ranny. Lekcja posłuszeństwa.", desc_en: "Muslims suffered losses when archers abandoned positions. The Prophet ﷺ was wounded. A lesson in obedience." },
  { year: "627 n.e.", hijri: "5 AH", pl: "Bitwa o Rów (Al-Khandaq)", en: "Battle of the Trench", desc_pl: "Na pomysł Salmana al-Farisiego wykopano rów wokół Medyny. Koalicja tysięcy wrogów odeszła bez walki.", desc_en: "On Salman al-Farisi's idea, a trench was dug around Madinah. A coalition of thousands retreated without fighting." },
  { year: "628 n.e.", hijri: "6 AH", pl: "Układ w Hudajbijja", en: "Treaty of Hudaybiyyah", desc_pl: "Traktat pokojowy z Mekkańczykami. Koran nazwał go 'wyraźnym zwycięstwem' (48:1).", desc_en: "Peace treaty with Meccans. The Quran called it a 'clear victory' (48:1)." },
  { year: "630 n.e.", hijri: "8 AH", pl: "Zdobycie Mekki", en: "Conquest of Mecca", desc_pl: "Wejście do Mekki prawie bez rozlewu krwi. Prorok ﷺ ogłosił powszechne przebaczenie.", desc_en: "Entry into Mecca with almost no bloodshed. The Prophet ﷺ declared a general amnesty." },
  { year: "632 n.e.", hijri: "10 AH", pl: "Pożegnalna Pielgrzymka i śmierć Proroka ﷺ", en: "Farewell Pilgrimage and death of Prophet ﷺ", desc_pl: "Ostatni Hajj — słynne Kazanie Pożegnalne. 8 czerwca 632 roku Prorok ﷺ odszedł do Allaha w wieku 63 lat.", desc_en: "Last Hajj — the famous Farewell Sermon. On June 8, 632, the Prophet ﷺ passed away at age 63." }
];

export const tajweedRules = [
  { id: "idgham", name_pl: "Idgham — Wtopienie", name_en: "Idgham — Assimilation", desc_pl: "Gdy nun sakin (نْ) lub tanwin spotka literę ي ن م و ل ر — łączymy je w jedno z dźwiękiem nosowym.", desc_en: "When nun sakin or tanwin meets ي ن م و ل ر — they merge into one with a nasal sound.", example_ar: "مَن يَقُولُ", example_tr: "man-yaqulu", letters: "ي ن م و ل ر", color: "#10b981" },
  { id: "ikhfa", name_pl: "Ikhfa — Ukrycie", name_en: "Ikhfa — Concealment", desc_pl: "Gdy nun sakin lub tanwin spotka jedną z 15 liter — wymawiamy z ukrytym dźwiękiem nosowym przez 2 haraki.", desc_en: "When nun sakin or tanwin meets one of 15 letters — pronounce with hidden nasal sound for 2 beats.", example_ar: "مَن كَانَ", example_tr: "man kaana", letters: "ت ث ج د ذ ز س ش ص ض ط ظ ف ق ك", color: "#f59e0b" },
  { id: "iqlab", name_pl: "Iqlab — Zamiana", name_en: "Iqlab — Conversion", desc_pl: "Gdy nun sakin lub tanwin spotka literę ب — zamieniamy na mim z ghunna (dźwiękiem nosowym).", desc_en: "When nun sakin or tanwin meets ب — convert the nun to mim with ghunnah.", example_ar: "مِن بَعْدِ", example_tr: "mim ba'di", letters: "ب", color: "#ef4444" },
  { id: "izhar", name_pl: "Izhar — Wymówienie wyraźne", name_en: "Izhar — Clear Pronunciation", desc_pl: "Gdy nun sakin lub tanwin spotka literę gardłową — wymawiamy wyraźnie bez ghunna.", desc_en: "When nun sakin or tanwin meets a throat letter — pronounce clearly without ghunnah.", example_ar: "مَنْ أَمَنَ", example_tr: "man amana", letters: "ء ه ع ح غ خ", color: "#3b82f6" },
  { id: "ghunna", name_pl: "Ghunna — Dźwięk nosowy", name_en: "Ghunnah — Nasalization", desc_pl: "Dźwięk nosowy przy م i ن z taszdid — trwa 2 haraki.", desc_en: "Nasal sound on م and ن with shaddah — lasts 2 beats.", example_ar: "إِنَّ", example_tr: "inna", letters: "م ن (z taszdid)", color: "#8b5cf6" },
  { id: "madd", name_pl: "Madd — Przedłużenie", name_en: "Madd — Elongation", desc_pl: "Przedłużenie samogłoski przy literach ا و ي. Podstawowy madd: 2 haraki, inne: 4-6 haraków.", desc_en: "Elongation at ا و ي. Basic madd: 2 beats, others: 4-6 beats.", example_ar: "قَالَ", example_tr: "qaala", letters: "ا و ي", color: "#06b6d4" },
  { id: "qalqalah", name_pl: "Qalqalah — Odbicie", name_en: "Qalqalah — Echoing", desc_pl: "Lekkie odbijające się brzmienie przy ق ط ب ج د gdy mają sukun lub są na końcu słowa.", desc_en: "Slight echoing sound on ق ط ب ج د with sukun or at end of word.", example_ar: "أَحَدٌ", example_tr: "ahad", letters: "ق ط ب ج د", color: "#ec4899" },
  { id: "waqf", name_pl: "Waqf — Pauza w recytacji", name_en: "Waqf — Pausing", desc_pl: "Zasady zatrzymywania się w recytacji. Znaki: م (musi), لا (nie), ج (można), قلى (lepiej).", desc_en: "Rules for stopping in recitation. Signs: م (must stop), لا (don't), ج (can stop), قلى (better to stop).", example_ar: "وَقف", example_tr: "waqf", letters: "م لا ج قلى ط", color: "#64748b" }
];

export const pillarsOfIslam = [
  { n: 1, ar: "الشَّهَادَة", tr: "Ash-Shahada", pl: "Wyznanie Wiary", en: "Declaration of Faith", desc_pl: "لَا إِلَهَ إِلَّا اللَّهُ مُحَمَّدٌ رَسُولُ اللَّهِ — Nie ma boga prócz Allaha, Muhammad jest Jego Posłańcem.", desc_en: "There is no god but Allah, Muhammad is His Messenger. Entry into Islam." },
  { n: 2, ar: "الصَّلَاة", tr: "As-Salah", pl: "Modlitwa", en: "Prayer", desc_pl: "5 modlitw dziennie: Fajr, Dhuhr, Asr, Maghrib, Isza. Bezpośrednia rozmowa z Allahem.", desc_en: "5 daily prayers: Fajr, Dhuhr, Asr, Maghrib, Isha. Direct conversation with Allah." },
  { n: 3, ar: "الزَّكَاة", tr: "Az-Zakah", pl: "Jałmużna Obowiązkowa", en: "Obligatory Charity", desc_pl: "2,5% majątku powyżej nisab rocznie dla potrzebujących. Oczyszcza majątek i serce.", desc_en: "2.5% of wealth above nisab annually for those in need. Purifies wealth and heart." },
  { n: 4, ar: "الصَّوْم", tr: "As-Sawm", pl: "Post", en: "Fasting", desc_pl: "Post w miesiącu Ramadan od świtu do zachodu słońca. Wstrzemięźliwość od jedzenia, picia i złych czynów.", desc_en: "Fasting in Ramadan from dawn to sunset. Abstaining from food, drink and bad deeds." },
  { n: 5, ar: "الْحَجّ", tr: "Al-Hajj", pl: "Pielgrzymka", en: "Pilgrimage", desc_pl: "Coroczna pielgrzymka do Mekki — obowiązek raz w życiu dla każdego kto ma możliwości.", desc_en: "Annual pilgrimage to Mecca — obligation once in a lifetime for those who are able." }
];

export const pillarsOfIman = [
  { n: 1, ar: "الإِيمَان بِاللَّه", tr: "Al-Iman billah", pl: "Wiara w Allaha", en: "Belief in Allah", desc_pl: "Wiara w jednego Boga — Allaha. Tawhed: jedność i wyjątkowość Boga.", desc_en: "Belief in one God — Allah. Tawhid: the oneness of God." },
  { n: 2, ar: "الإِيمَان بِالْمَلَائِكَة", tr: "Al-Iman bil-mala'ika", pl: "Wiara w Aniołów", en: "Belief in Angels", desc_pl: "Aniołowie stworzeni ze światła. Najważniejsi: Dżibril (objawienie), Mikail (deszcz), Israfil (trąba sądu).", desc_en: "Angels created from light. Key: Jibreel (revelation), Mikail (rain), Israfil (trumpet of judgment)." },
  { n: 3, ar: "الإِيمَان بِالْكُتُب", tr: "Al-Iman bil-kutub", pl: "Wiara w Księgi Objawione", en: "Belief in the Revealed Books", desc_pl: "Wiara we wszystkie księgi zesłane przez Allaha: Koran, Tora, Ewangelia, Psalmy.", desc_en: "Belief in all books sent by Allah: Quran, Torah, Gospel, Psalms." },
  { n: 4, ar: "الإِيمَان بِالرُّسُل", tr: "Al-Iman bir-rusul", pl: "Wiara w Proroków", en: "Belief in the Prophets", desc_pl: "Wiara we wszystkich proroków — od Adama przez Ibrahima, Musę, Isę aż do Muhammada ﷺ.", desc_en: "Belief in all prophets — from Adam through Ibrahim, Musa, Isa to Muhammad ﷺ." },
  { n: 5, ar: "الإِيمَان بِالْيَوْمِ الْآخِر", tr: "Al-Iman bil-yawmil-akhir", pl: "Wiara w Dzień Ostatni", en: "Belief in the Last Day", desc_pl: "Wiara w Dzień Sądu, raj (Janna) i piekło (Dżahannam). Każdy człowiek będzie rozliczony.", desc_en: "Belief in the Day of Judgment, paradise and hellfire. Every person will be accountable." },
  { n: 6, ar: "الإِيمَان بِالْقَدَر", tr: "Al-Iman bil-qadar", pl: "Wiara w Przeznaczenie", en: "Belief in Divine Decree", desc_pl: "Allah wie wszystko co było, jest i będzie. Tawakkul: ufanie Allahowi przy jednoczesnym działaniu.", desc_en: "Allah knows everything that was, is and will be. Tawakkul: trust in Allah while still acting." }
];

export const islamicMonths = [
  { n: 1, ar: "مُحَرَّم", tr: "Muharram", pl: "Muharram", en: "Muharram", note_pl: "Pierwszy miesiąc. Dzień Aszura (10.) — post i refleksja.", note_en: "First month. Day of Ashura (10th) — fasting and reflection." },
  { n: 2, ar: "صَفَر", tr: "Safar", pl: "Safar", en: "Safar", note_pl: "Drugi miesiąc.", note_en: "Second month." },
  { n: 3, ar: "رَبِيعُ الْأَوَّل", tr: "Rabi al-Awwal", pl: "Rabi al-Awwal", en: "Rabi al-Awwal", note_pl: "Trzeci miesiąc. 12. — Mawlid an-Nabi: narodziny Proroka ﷺ.", note_en: "Third month. 12th — Mawlid an-Nabi: birth of the Prophet ﷺ." },
  { n: 4, ar: "رَبِيعُ الثَّانِي", tr: "Rabi ath-Thani", pl: "Rabi ath-Thani", en: "Rabi ath-Thani", note_pl: "Czwarty miesiąc.", note_en: "Fourth month." },
  { n: 5, ar: "جُمَادَى الْأُولَى", tr: "Jumada al-Ula", pl: "Jumada al-Ula", en: "Jumada al-Ula", note_pl: "Piąty miesiąc.", note_en: "Fifth month." },
  { n: 6, ar: "جُمَادَى الْآخِرَة", tr: "Jumada al-Akhira", pl: "Jumada al-Akhira", en: "Jumada al-Akhira", note_pl: "Szósty miesiąc.", note_en: "Sixth month." },
  { n: 7, ar: "رَجَب", tr: "Rajab", pl: "Rajab", en: "Rajab", note_pl: "Siódmy miesiąc. Jeden z czterech świętych miesięcy. 27. — Isra wal-Mi'radż.", note_en: "Seventh month. One of four sacred months. 27th — Isra wal-Mi'raj." },
  { n: 8, ar: "شَعْبَان", tr: "Sha'ban", pl: "Sha'ban", en: "Sha'ban", note_pl: "Ósmy miesiąc. 15. — Laylat al-Bara'a. Miesiąc przygotowania przed Ramadanem.", note_en: "Eighth month. 15th — Night of Bara'at. Month of preparation before Ramadan." },
  { n: 9, ar: "رَمَضَان", tr: "Ramadan", pl: "Ramadan", en: "Ramadan", note_pl: "Dziewiąty miesiąc. Miesiąc postu i Koranu. Laylat al-Qadr w ostatnich 10 nocach.", note_en: "Ninth month. Month of fasting and Quran. Laylat al-Qadr in the last 10 nights." },
  { n: 10, ar: "شَوَّال", tr: "Shawwal", pl: "Shawwal", en: "Shawwal", note_pl: "Dziesiąty miesiąc. 1. — Eid al-Fitr. 6 dni postu = post całego roku.", note_en: "Tenth month. 1st — Eid al-Fitr. 6 days fasting = reward of fasting a whole year." },
  { n: 11, ar: "ذُو الْقَعْدَة", tr: "Dhu al-Qi'dah", pl: "Dhu al-Qi'dah", en: "Dhu al-Qi'dah", note_pl: "Jedenasty miesiąc. Jeden z czterech świętych miesięcy.", note_en: "Eleventh month. One of four sacred months." },
  { n: 12, ar: "ذُو الْحِجَّة", tr: "Dhu al-Hijjah", pl: "Dhu al-Hijjah", en: "Dhu al-Hijjah", note_pl: "Dwunasty miesiąc. 8-13. — Hajj. 10. — Eid al-Adha. Jeden z czterech świętych miesięcy.", note_en: "Twelfth month. 8th-13th — Hajj. 10th — Eid al-Adha. One of four sacred months." }
];

export const arabicRoots = [
  { root: "ك-ت-ب", root_ar: "ك ت ب", tr: "k-t-b", meaning_pl: "pisanie", meaning_en: "writing", words: [
    { ar: "كَتَبَ", tr: "kataba", pl: "pisał", en: "he wrote" },
    { ar: "كِتَاب", tr: "kitab", pl: "książka", en: "book" },
    { ar: "كَاتِب", tr: "katib", pl: "pisarz", en: "writer" },
    { ar: "مَكْتَبَة", tr: "maktaba", pl: "biblioteka", en: "library" }
  ]},
  { root: "ع-ل-م", root_ar: "ع ل م", tr: "'a-l-m", meaning_pl: "wiedza", meaning_en: "knowledge", words: [
    { ar: "عِلْم", tr: "'ilm", pl: "wiedza", en: "knowledge" },
    { ar: "عَالِم", tr: "'alim", pl: "uczony", en: "scholar" },
    { ar: "تَعَلَّمَ", tr: "ta'allama", pl: "uczył się", en: "he learned" },
    { ar: "مَعْلُوم", tr: "ma'lum", pl: "znany", en: "known" }
  ]},
  { root: "د-ر-س", root_ar: "د ر س", tr: "d-r-s", meaning_pl: "nauka", meaning_en: "study", words: [
    { ar: "دَرَسَ", tr: "darasa", pl: "uczył się", en: "he studied" },
    { ar: "دَرْس", tr: "dars", pl: "lekcja", en: "lesson" },
    { ar: "مَدْرَسَة", tr: "madrasa", pl: "szkoła", en: "school" },
    { ar: "مُدَرِّس", tr: "mudarris", pl: "nauczyciel", en: "teacher" }
  ]},
  { root: "س-ل-م", root_ar: "س ل م", tr: "s-l-m", meaning_pl: "pokój/bezpieczeństwo", meaning_en: "peace/safety", words: [
    { ar: "سَلَام", tr: "salam", pl: "pokój", en: "peace" },
    { ar: "إِسْلَام", tr: "islam", pl: "islam", en: "Islam" },
    { ar: "مُسْلِم", tr: "muslim", pl: "muzułmanin", en: "Muslim" },
    { ar: "سَلَامة", tr: "salama", pl: "bezpieczeństwo", en: "safety" }
  ]},
  { root: "ق-ر-أ", root_ar: "ق ر أ", tr: "q-r-'", meaning_pl: "czytanie", meaning_en: "reading", words: [
    { ar: "قَرَأَ", tr: "qara'a", pl: "czytał", en: "he read" },
    { ar: "قُرْآن", tr: "qur'an", pl: "Koran", en: "Quran" },
    { ar: "قِرَاءَة", tr: "qira'a", pl: "czytanie", en: "reading" },
    { ar: "قَارِئ", tr: "qari'", pl: "recytator", en: "reciter" }
  ]},
  { root: "ح-م-د", root_ar: "ح م د", tr: "h-m-d", meaning_pl: "chwała", meaning_en: "praise", words: [
    { ar: "حَمْد", tr: "hamd", pl: "chwała", en: "praise" },
    { ar: "أَحْمَد", tr: "Ahmad", pl: "Ahmad (imię Proroka)", en: "Ahmad (name of the Prophet)" },
    { ar: "مُحَمَّد", tr: "Muhammad", pl: "Muhammad", en: "Muhammad" },
    { ar: "حَمِيد", tr: "hamid", pl: "godny chwały", en: "praiseworthy" }
  ]},
  { root: "ر-ح-م", root_ar: "ر ح م", tr: "r-h-m", meaning_pl: "miłosierdzie", meaning_en: "mercy", words: [
    { ar: "رَحْمَة", tr: "rahma", pl: "miłosierdzie", en: "mercy" },
    { ar: "رَحْمَن", tr: "rahman", pl: "Miłosierny", en: "Most Gracious" },
    { ar: "رَحِيم", tr: "rahim", pl: "Miłościwy", en: "Most Merciful" },
    { ar: "أَرْحَام", tr: "arham", pl: "więzy krwi", en: "blood ties" }
  ]},
  { root: "ص-ب-ر", root_ar: "ص ب ر", tr: "s-b-r", meaning_pl: "cierpliwość", meaning_en: "patience", words: [
    { ar: "صَبْر", tr: "sabr", pl: "cierpliwość", en: "patience" },
    { ar: "صَابِر", tr: "sabir", pl: "cierpliwy", en: "patient" },
    { ar: "صَبُور", tr: "sabur", pl: "bardzo cierpliwy", en: "very patient" },
    { ar: "إِصْبَار", tr: "isbara", pl: "wykazywać cierpliwość", en: "to show patience" }
  ]}
];

// ============================================================
// NEW MUSLIM GUIDE — muallaf
// ============================================================
export const newMuslimSteps = [
  {
    n: 1, icon: "☪",
    ar: "أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا ٱللَّٰهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ ٱللَّٰهِ",
    tr: "Ašhadu an lā ilāha illā-llāh, wa ašhadu anna Muḥammadan rasūlu-llāh",
    titlePl: "Szahada — Wyznanie Wiary",
    titleEn: "Shahada — Declaration of Faith",
    descPl: "Pierwsze i najważniejsze. Znaczy: «Świadczę, że nie ma boga prócz Allaha i świadczę, że Muhammad jest Jego posłańcem.» Wypowiedziana szczerze — jest momentem, w którym stajesz się muzułmaninem.",
    descEn: "First and most important. It means: 'I bear witness there is no god but Allah and Muhammad is His messenger.' Said sincerely — it is the moment you become Muslim.",
    tipPl: "Nie musisz rozumieć arabskiego idealnie. Liczy się szczerość serca (niyyah).",
    tipEn: "You don't need perfect Arabic. What counts is sincerity of heart (niyyah)."
  },
  {
    n: 2, icon: "💧",
    ar: "الوُضُوء",
    tr: "al-wuḍūʾ",
    titlePl: "Wudu — Oczyszczenie",
    titleEn: "Wudu — Ritual Purification",
    descPl: "Bez wudu modlitwa jest nieważna. Na szczęście to proste: myjesz ręce, usta, nos, twarz, przedramiona, głowę, uszy i stopy — w określonej kolejności. Trwa ok. 2 minut.",
    descEn: "Without wudu prayer is invalid. Fortunately it's simple: wash hands, mouth, nose, face, forearms, head, ears and feet — in order. Takes about 2 minutes.",
    tipPl: "Wudu trwa do momentu gdy coś je 'złamie' — sen, wyjście do toalety, utrata przytomności.",
    tipEn: "Wudu stays valid until 'broken' — by sleep, using the bathroom, or losing consciousness."
  },
  {
    n: 3, icon: "📖",
    ar: "الفَاتِحَة",
    tr: "al-Fātiḥa",
    titlePl: "Al-Fatiha — Zanim zaczniesz się modlić",
    titleEn: "Al-Fatiha — Before You Start Praying",
    descPl: "7 wersetów, które recytujesz w każdej jednostce modlitwy (raka'at). To pierwsza sura, której należy się nauczyć. Zacznij od niej — reszta może poczekać.",
    descEn: "7 verses recited in every prayer unit (raka'at). This is the first surah to learn. Start here — the rest can wait.",
    tipPl: "Dopuszczalne jest czytanie Al-Fatiha z kartki lub telefonu, gdy dopiero zaczynasz.",
    tipEn: "It's acceptable to read Al-Fatiha from a card or phone when you're just starting out."
  },
  {
    n: 4, icon: "🕌",
    ar: "الصَّلَاة",
    tr: "aṣ-Ṣalāh",
    titlePl: "Salat — 5 Modlitw Dziennie",
    titleEn: "Salat — 5 Daily Prayers",
    descPl: "Fajr (świt), Dhuhr (południe), Asr (popołudnie), Maghrib (zachód słońca), Isha (noc). Nie martw się, że zrobisz błąd — Allah ocenia intencję i wysiłek, nie perfekcję.",
    descEn: "Fajr (dawn), Dhuhr (noon), Asr (afternoon), Maghrib (sunset), Isha (night). Don't worry about making mistakes — Allah judges intention and effort, not perfection.",
    tipPl: "Możesz łączyć modlitwy w podróży lub chorobie — islam jest religią ułatwień.",
    tipEn: "You may combine prayers while travelling or ill — Islam is a religion of ease."
  },
  {
    n: 5, icon: "🌙",
    ar: "الصِّيَام",
    tr: "aṣ-Ṣiyām",
    titlePl: "Ramadan — Post",
    titleEn: "Ramadan — Fasting",
    descPl: "Raz w roku, przez cały miesiąc Ramadan, muzułmanie powstrzymują się od jedzenia, picia i współżycia od świtu do zachodu słońca. To czas duchowości, wspólnoty i wdzięczności.",
    descEn: "Once a year, throughout Ramadan, Muslims abstain from food, drink and intimacy from dawn to sunset. It is a time of spirituality, community and gratitude.",
    tipPl: "Chorzy, podróżni i kobiety w ciąży są zwolnieni — mogą odpracować dni później.",
    tipEn: "The sick, travellers and pregnant women are exempt — they can make up days later."
  },
  {
    n: 6, icon: "🤲",
    ar: "الزَّكَاة",
    tr: "az-Zakāh",
    titlePl: "Zakat — Jałmużna",
    titleEn: "Zakat — Almsgiving",
    descPl: "2,5% rocznych oszczędności przekazywane potrzebującym — jeśli posiadasz nadwyżkę przez cały rok. To oczyszczenie majątku i filar solidarności społecznej w islamie.",
    descEn: "2.5% of annual savings given to those in need — if you've held a surplus for a full year. It purifies wealth and is a pillar of social solidarity in Islam.",
    tipPl: "Nie dotyczy kogoś, kto nie ma nadwyżek finansowych. Islam nie nakłada ciężarów.",
    tipEn: "Doesn't apply to someone without financial surplus. Islam does not burden people."
  },
  {
    n: 7, icon: "🕋",
    ar: "الحَج",
    tr: "al-Ḥajj",
    titlePl: "Hadżdż — Pielgrzymka",
    titleEn: "Hajj — Pilgrimage",
    descPl: "Raz w życiu, jeśli możesz sobie na to pozwolić zdrowotnie i finansowo. Miliony muzułmanów z całego świata spotykają się w Mekce — jedno z najpotężniejszych doświadczeń duchowych na ziemi.",
    descEn: "Once in a lifetime, if you are physically and financially able. Millions of Muslims from around the world gather in Mecca — one of the most powerful spiritual experiences on earth.",
    tipPl: "Nikt nie jest zobowiązany do Hadżdżu jeśli go nie stać lub choruje. Allah jest Al-Latif — subtelny i wyrozumiały.",
    tipEn: "No one is obligated for Hajj if they cannot afford it or are ill. Allah is Al-Latif — gentle and understanding."
  }
];

// ============================================================
// HALAL & HARAM DATA
// ============================================================
export const halalHaramData = {
  food: [
    { status: "halal", icon: "🐟", namePl: "Ryby i owoce morza", nameEn: "Fish and seafood", ar: "السَّمَك", tr: "as-samak", reasonPl: "Wszystkie ryby i większość owoców morza są halal — bez konieczności specjalnego uboju.", reasonEn: "All fish and most seafood are halal — no special slaughter needed.", ref: "Quran 5:96" },
    { status: "halal", icon: "🥬", namePl: "Warzywa i owoce", nameEn: "Vegetables and fruit", ar: "الخُضْرَوَات", tr: "al-khuḍrawāt", reasonPl: "Wszystkie rośliny są halal. Bez wyjątków.", reasonEn: "All plants are halal. No exceptions.", ref: "" },
    { status: "halal", icon: "🐄", namePl: "Mięso halal (dhabihah)", nameEn: "Halal meat (dhabihah)", ar: "ذَبِيحَة", tr: "dhabīḥa", reasonPl: "Bydło, owce, kozy, drób — halal jeśli ubite z wymówieniem bismillah jednym cięciem. Szukaj certyfikatu halal.", reasonEn: "Cattle, sheep, goats, poultry — halal if slaughtered saying bismillah with one cut. Look for halal certification.", ref: "Quran 6:121" },
    { status: "haram", icon: "🐷", namePl: "Wieprzowina", nameEn: "Pork", ar: "لَحْمُ الخِنْزِير", tr: "laḥm al-khinzīr", reasonPl: "Jasno zakazana w Qur'anie. Dotyczy też żelatyny wieprzowej, smalcu i wszelkich produktów z wieprzowiny.", reasonEn: "Clearly forbidden in the Quran. Applies also to pork gelatin, lard and all pork-derived products.", ref: "Quran 2:173" },
    { status: "haram", icon: "🩸", namePl: "Krew", nameEn: "Blood", ar: "الدَّم", tr: "ad-dam", reasonPl: "Przepływająca krew jest haram. Dlatego ubój halal wymaga pełnego wykrwawienia zwierzęcia.", reasonEn: "Flowing blood is haram. This is why halal slaughter requires full bleeding of the animal.", ref: "Quran 2:173" },
    { status: "haram", icon: "🦁", namePl: "Drapieżniki i padlina", nameEn: "Predators and carrion", ar: "الجَوَارِح", tr: "al-jawāriḥ", reasonPl: "Zwierzęta z kłami lub pazurami (lwy, psy, koty) oraz martwe zwierzęta (padlina) są haram.", reasonEn: "Animals with fangs or talons (lions, dogs, cats) and already dead animals (carrion) are haram.", ref: "Bukhari 5530" },
    { status: "makruh", icon: "🦐", namePl: "Krewetki (kwestia sporna)", nameEn: "Shrimp (disputed)", ar: "الرَّوْبِيَان", tr: "ar-rawbiyān", reasonPl: "Halal wg Szafi'i i Hanbali; makruh wg Hanafi. Ogromna większość muzułmanów je je bez problemu.", reasonEn: "Halal according to Shafi'i and Hanbali; makruh according to Hanafi. The vast majority of Muslims eat them without issue.", ref: "" }
  ],
  drinks: [
    { status: "haram", icon: "🍺", namePl: "Alkohol i każdy środek odurzający", nameEn: "Alcohol and any intoxicant", ar: "الخَمْر", tr: "al-khamr", reasonPl: "Każda ilość alkoholu jest haram — nie tylko upijanie się. «Co w dużych ilościach odurzą — w małych też jest haram.» (Abu Dawud)", reasonEn: "Any amount of alcohol is haram — not just getting drunk. 'Whatever intoxicates in large amounts — a small amount is also haram.' (Abu Dawud)", ref: "Quran 5:90" },
    { status: "halal", icon: "☕", namePl: "Kawa i herbata", nameEn: "Coffee and tea", ar: "القَهْوَة والشَّاي", tr: "al-qahwa wa-š-šāy", reasonPl: "W pełni halal. Kofeina nie jest środkiem odurzającym w rozumieniu islamskim.", reasonEn: "Fully halal. Caffeine is not an intoxicant in the Islamic sense.", ref: "" },
    { status: "halal", icon: "🧃", namePl: "Soki, woda, napoje bezalkoholowe", nameEn: "Juices, water, soft drinks", ar: "العَصِير", tr: "al-ʿaṣīr", reasonPl: "Wszystkie napoje niealkoholowe są halal — soki, woda, napoje gazowane, energetyki (bez alkoholu).", reasonEn: "All non-alcoholic drinks are halal — juices, water, fizzy drinks, energy drinks (without alcohol).", ref: "" },
    { status: "makruh", icon: "🍹", namePl: "Napoje przypominające alkohol smakiem", nameEn: "Drinks imitating alcohol in taste", ar: "", tr: "", reasonPl: "Bezalkoholowe piwo lub «wino» — technicznie halal jeśli 0% alkoholu, ale makruh (niepolecane) bo imituje haram.", reasonEn: "Non-alcoholic beer or 'wine' — technically halal if 0% alcohol, but makruh (discouraged) as it imitates haram.", ref: "" }
  ],
  behavior: [
    { status: "haram", icon: "🎰", namePl: "Hazard", nameEn: "Gambling", ar: "المَيْسِر", tr: "al-maysir", reasonPl: "Wszystkie formy hazardu — kasyna, zakłady, loterie. Islam chroni majątek przed ryzykiem i uzależnieniem.", reasonEn: "All forms of gambling — casinos, bets, lotteries. Islam protects wealth from risk and addiction.", ref: "Quran 5:90" },
    { status: "haram", icon: "💸", namePl: "Lichwiarskie odsetki (riba)", nameEn: "Usurious interest (riba)", ar: "الرِّبَا", tr: "ar-ribā", reasonPl: "Pożyczanie pieniędzy na procent jest zakazane. Islamskie finanse oferują alternatywy (murabaha, ijara).", reasonEn: "Lending money at interest is forbidden. Islamic finance offers alternatives (murabaha, ijara).", ref: "Quran 2:275" },
    { status: "haram", icon: "🗣", namePl: "Plotkowanie i obmowa (ghiba)", nameEn: "Gossip and backbiting (ghiba)", ar: "الغِيبَة", tr: "al-ghība", reasonPl: "Mówienie o kimś za jego plecami rzeczy, których by nie lubił — nawet jeśli prawdziwych. Quran porównuje to do jedzenia ciała brata.", reasonEn: "Talking about someone behind their back with things they would dislike — even if true. The Quran compares it to eating your brother's flesh.", ref: "Quran 49:12" },
    { status: "haram", icon: "🚫", namePl: "Seks poza małżeństwem (zina)", nameEn: "Sex outside marriage (zina)", ar: "الزِّنَا", tr: "az-zinā", reasonPl: "Cudzołóstwo i przedmałżeńskie współżycie są haram. Islam chroni rodzinę i stabilność społeczną.", reasonEn: "Adultery and premarital sex are haram. Islam protects the family and social stability.", ref: "Quran 17:32" },
    { status: "halal", icon: "💑", namePl: "Współżycie w małżeństwie", nameEn: "Marital intimacy", ar: "النِّكَاح", tr: "an-nikāḥ", reasonPl: "Małżeństwo jest sunnah Proroka ﷺ. Współżycie małżeńskie jest aktem kultu (ibadah) gdy jest z dobrą intencją.", reasonEn: "Marriage is the sunnah of the Prophet ﷺ. Marital relations are an act of worship (ibadah) when done with good intention.", ref: "Muslim 1400" },
    { status: "haram", icon: "🤥", namePl: "Kłamstwo i oszustwo", nameEn: "Lying and cheating", ar: "الكَذِب", tr: "al-kaḏib", reasonPl: "Prorok ﷺ powiedział: «Wierny może być tchórzliwy, skąpy lub grzesznikiem — ale nie kłamcą.» (Ahmad). Uczciwość (sidq) to fundament islamskiego charakteru.", reasonEn: "The Prophet ﷺ said: 'A believer can be a coward, miser or sinner — but not a liar.' (Ahmad). Honesty (sidq) is a foundation of Islamic character.", ref: "Ahmad 8925" }
  ],
  gray: [
    { icon: "🔍", questionPl: "Czy żelatyna (E441) jest halal?", questionEn: "Is gelatin (E441) halal?", answerPl: "Zależy od źródła. Żelatyna wieprzowa — haram. Wołowa (halal) lub rybia — halal. Żelatyna syntetyczna — halal. Sprawdzaj etykiety lub szukaj certyfikatu. Aplikacje jak «Halal Checker» skanują E-numery automatycznie.", answerEn: "Depends on the source. Pork gelatin — haram. Beef (halal) or fish — halal. Synthetic gelatin — halal. Check labels or look for certification. Apps like 'Halal Checker' scan E-numbers automatically." },
    { icon: "🔍", questionPl: "Czy mogę jeść mięso z polskiego supermarketu?", questionEn: "Can I eat meat from a Polish supermarket?", answerPl: "Wg madhhab Szafi'i: mięso Ludzi Księgi (chrześcijańskie/żydowskie) jest dopuszczalne gdy halal niedostępne. Wg bardziej rygorystycznych szkół — tylko certyfikowane halal. W Polsce sklepy halal znajdziesz w większych miastach. W razie wątpliwości — wybierz rybę lub wegetariańskie.", answerEn: "According to the Shafi'i madhab: meat from People of the Book (Christian/Jewish) is acceptable when halal is unavailable. Stricter schools require halal certification only. In Poland, halal shops are available in major cities. When in doubt — choose fish or vegetarian." },
    { icon: "🔍", questionPl: "Które E-numery są podejrzane?", questionEn: "Which E-numbers are suspicious?", answerPl: "Podejrzane: E120 (karmin z owadów — haram), E441 (żelatyna — zależy od źródła), E471 (mono- i diglicerydy — mogą być wieprzowe), E542 (fosfoран костный — może być wieprzowy). Aplikacja «Halal Checker» robi to automatycznie za ciebie.", answerEn: "Suspicious: E120 (carmine from insects — haram), E441 (gelatin — depends on source), E471 (mono- and diglycerides — may be porcine), E542 (edible bone phosphate — may be porcine). The 'Halal Checker' app does this automatically for you." },
    { icon: "🔍", questionPl: "Co z lekami zawierającymi alkohol lub żelatynę?", questionEn: "What about medicines containing alcohol or gelatin?", answerPl: "Konieczność (darura) uchyla zakaz — jeśli jedyna dostępna wersja leku zawiera haram składnik, a zdrowie tego wymaga, jest to dozwolone. Islam jest religią łatwości: «Allah chce dla was łatwości, nie trudności» (Quran 2:185). Zapytaj lekarza o alternatywy jeśli są dostępne.", answerEn: "Necessity (darura) overrides prohibition — if the only available medicine contains a haram ingredient and health requires it, it is permitted. Islam is a religion of ease: 'Allah wants ease for you, not hardship' (Quran 2:185). Ask your doctor about alternatives if available." }
  ]
};

// ============================================================
// ISLAMIC FAQ — islamfaq
// ============================================================
export const islamicFaq = [
  // ── myths ──
  { id: "worship_muhammad", tab: "myths", verdict: "false",
    qPl: "Czy muzułmanie czczą Muhammada jak boga?",
    qEn: "Do Muslims worship Muhammad as a god?",
    aPl: "Absolutnie nie. Szahada mówi: «Nie ma boga prócz Allaha i Muhammad jest Jego posłańcem.» Muhammad ﷺ był człowiekiem — prorokiem i przykładem, ale nie boskim. Gdy Omar ibn al-Khattab usłyszał o śmierci Proroka i chciał zaprzeczyć, Abu Bakr powiedział: «Kto czcił Muhammada — Muhammad umarł. Kto czci Allaha — Allah żyje i nie umiera.» (Bukhari 3668)",
    aEn: "Absolutely not. The Shahada says: 'There is no god but Allah and Muhammad is His messenger.' Muhammad ﷺ was a human — a prophet and example, but not divine. When Omar ibn al-Khattab wanted to deny the Prophet's death, Abu Bakr said: 'Whoever worshipped Muhammad — Muhammad has died. Whoever worships Allah — Allah lives and does not die.' (Bukhari 3668)",
    ref: "Quran 3:144" },
  { id: "sword", tab: "myths", verdict: "complex",
    qPl: "Czy islam szerzył się mieczem?",
    qEn: "Was Islam spread by the sword?",
    aPl: "Nie w przypadku największego skupiska muzułmanów — Azji Południowo-Wschodniej (Indonezja, Malezja). Tam islam przyszedł przez arabskich i indyjskich kupców oraz sufickich mistrzów — bez jednej armii. Były podboje militarne (jak wszystkie ówczesne cywilizacje), ale zasada jest jasna: «Nie ma przymusu w religii» (Quran 2:256). Nawet własny wujek Proroka ﷺ, Abu Talib, umarł niebędąc muzułmaninem — nikt go nie zmuszał.",
    aEn: "Not in the case of the world's largest Muslim population — Southeast Asia (Indonesia, Malaysia). There Islam came through Arab and Indian merchants and Sufi masters — without a single army. There were military conquests (as with all civilisations of the time), but the principle is clear: 'There is no compulsion in religion' (Quran 2:256). Even the Prophet's ﷺ own uncle, Abu Talib, died a non-Muslim — no one coerced him.",
    ref: "Quran 2:256" },
  { id: "arabs", tab: "myths", verdict: "false",
    qPl: "Czy wszyscy muzułmanie są Arabami?",
    qEn: "Are all Muslims Arabs?",
    aPl: "Tylko ok. 20% spośród 1,8 miliarda muzułmanów to Arabowie. Indonezja ma ponad 270 milionów muzułmanów i jest największym krajem muzułmańskim na świecie. Islam jest globalny: Pakistan, Bangladesz, Nigeria, Turcja, Chiny, Bośnia, Polska — wszędzie są muzułmanie różnych ras i kultur.",
    aEn: "Only about 20% of 1.8 billion Muslims are Arab. Indonesia has over 270 million Muslims and is the world's largest Muslim-majority country. Islam is global: Pakistan, Bangladesh, Nigeria, Turkey, China, Bosnia, Poland — everywhere there are Muslims of different races and cultures.",
    ref: "" },
  { id: "animals", tab: "myths", verdict: "false",
    qPl: "Czy muzułmanie uprawiają seks ze zwierzętami?",
    qEn: "Do Muslims have sex with animals?",
    aPl: "To kłamstwo i celowa dehumanizacja. Stosunek ze zwierzęciem jest absolutnie haram w islamie i historycznie był karany w prawie islamskim. Jest to jeden z najbardziej szerzonych islamofobicznych stereotypów, niemający żadnego oparcia w rzeczywistości ani w religii. Muzułmanie mają ogromny szacunek dla zwierząt — hadisy mówią o nagrodzie dla kogoś, kto nakarmi spragnionego psa.",
    aEn: "This is a lie and deliberate dehumanisation. Intercourse with animals is absolutely haram in Islam and was historically punishable under Islamic law. It is one of the most widely spread Islamophobic stereotypes with no basis in reality or religion. Muslims have great respect for animals — hadiths speak of reward for someone who gives water to a thirsty dog.",
    ref: "Bukhari 2363" },
  { id: "music", tab: "myths", verdict: "complex",
    qPl: "Czy muzyka jest zakazana w islamie?",
    qEn: "Is music forbidden in Islam?",
    aPl: "To kwestia sporna — uczeni różnią się zdaniami od wieków. Jedni (Hanbali) uważają muzykę instrumentalną za makruh lub haram; inni (Maliki, część Szafi'i) dopuszczają ją. Quran nie zakazuje muzyki wprost. Zakazane jest to, co prowadzi do grzechu (sprośne teksty, nadużycie). Większość muzułmanów słucha muzyki bez problemów.",
    aEn: "This is a disputed issue — scholars have disagreed for centuries. Some (Hanbali) consider instrumental music makruh or haram; others (Maliki, some Shafi'i) permit it. The Quran does not explicitly forbid music. What is forbidden is what leads to sin (obscene lyrics, excess). Most Muslims listen to music without issue.",
    ref: "" },

  // ── women ──
  { id: "wife_beating", tab: "women", verdict: "false",
    qPl: "Czy islam pozwala mężom bić żony?",
    qEn: "Does Islam permit husbands to beat their wives?",
    aPl: "Nie — to jeden z największych mitów o islamie. Werset Quran 4:34 używa arabskiego słowa «daraba» — które klasyczni uczeni tłumaczyli różnie (od «odejść» po «symboliczne dotknięcie»), ale Prorok ﷺ nigdy nie uderzył żadnej kobiety ani zwierzęcia. Powiedział wprost: «Najlepszy z was jest ten, kto jest najlepszy dla swojej żony» (Tirmidhi 1162). Bukhari cytuje Proroka: «Jak może ktokolwiek bić żonę jak biją się niewolnicy, a potem z nią spać?» Przemoc domowa jest haram.",
    aEn: "No — this is one of the greatest myths about Islam. Quran verse 4:34 uses the Arabic word 'daraba' — which classical scholars translated differently (from 'to leave' to a 'symbolic touch'), but the Prophet ﷺ never struck any woman or animal. He said clearly: 'The best of you is he who is best to his wife' (Tirmidhi 1162). Bukhari quotes the Prophet: 'How can anyone beat his wife as slaves are beaten, and then sleep with her?' Domestic violence is haram.",
    ref: "Tirmidhi 1162, Bukhari 4942" },
  { id: "womens_rights", tab: "women", verdict: "false",
    qPl: "Czy islam odbiera kobietom prawa?",
    qEn: "Does Islam strip women of their rights?",
    aPl: "Wręcz przeciwnie — w VII-wiecznej Arabii islam był rewolucją praw kobiet. Islam dał kobietom prawo do własności, dziedziczenia (pierwsze w historii), inicjowania rozwodu (khul') i nauki. Khadijah, pierwsza żona Proroka ﷺ, była zamożną przedsiębiorcą i to ona zaproponowała mu małżeństwo. Aisza bint Abi Bakr była największym uczonym hadisów swojej epoki. Problemy z prawami kobiet w krajach muzułmańskich to najczęściej kultura i polityka — nie islam.",
    aEn: "On the contrary — in 7th-century Arabia, Islam was a revolution in women's rights. Islam gave women the right to own property, to inheritance (first in history), to initiate divorce (khul') and to education. Khadijah, the Prophet's ﷺ first wife, was a wealthy businesswoman who proposed to him. Aisha bint Abi Bakr was the greatest hadith scholar of her era. Issues with women's rights in Muslim countries are most often culture and politics — not Islam.",
    ref: "Quran 4:32" },
  { id: "hijab", tab: "women", verdict: "complex",
    qPl: "Czy hidżab jest przymusem?",
    qEn: "Is the hijab forced?",
    aPl: "W islamie hidżab jest nakazem religijnym (jak modlitwa czy post). Ale: «Nie ma przymusu w religii» (Quran 2:256) — nikt nie może być do wiary zmuszony. Wiele muzułmanek nosi hidżab z własnego wyboru i jest z niego dumna. Przymus hidżabu w Iranie czy Arabii Saudyjskiej to decyzja polityczna tamtych państw — nie islamska zasada. Prorok ﷺ nigdy nikogo nie zmuszał.",
    aEn: "In Islam, hijab is a religious requirement (like prayer or fasting). But: 'There is no compulsion in religion' (Quran 2:256) — no one can be coerced into faith. Many Muslim women wear hijab by choice and are proud of it. Forced hijab in Iran or Saudi Arabia is a political decision of those states — not an Islamic principle. The Prophet ﷺ never coerced anyone.",
    ref: "Quran 2:256, 24:31" },
  { id: "polygamy", tab: "women", verdict: "complex",
    qPl: "Co z poligamią w islamie?",
    qEn: "What about polygamy in Islam?",
    aPl: "Islam ograniczył poligamię, nie wprowadził ją — przed islamem mężczyźni brali dowolną liczbę żon. Quran pozwala na max. 4 żony, ale pod warunkiem absolutnie sprawiedliwego traktowania — i zaraz dodaje: «Nie będziecie w stanie być sprawiedliwi, nawet jeśli chcecie» (4:129). Większość muzułmańskich uczonych uznaje to za praktyczne zniechęcenie do poligamii. Dziś poligamia jest rzadkością i zakazana prawnie w wielu krajach muzułmańskich.",
    aEn: "Islam limited polygamy, it did not introduce it — before Islam men took any number of wives. The Quran permits up to 4 wives, but only with absolutely equal treatment — and then immediately adds: 'You will not be able to be just, even if you wish' (4:129). Most Muslim scholars consider this a practical discouragement of polygamy. Today polygamy is rare and legally prohibited in many Muslim countries.",
    ref: "Quran 4:3, 4:129" },

  // ── religions ──
  { id: "jesus", tab: "religions", verdict: "info",
    qPl: "Co islam mówi o Jezusie?",
    qEn: "What does Islam say about Jesus?",
    aPl: "Jezus — Isa ibn Maryam (Jezus syn Marii) — jest jednym z pięciu najważniejszych proroków w islamie (obok Noe, Abrahama, Mojżesza i Muhammada). Islam potwierdza: dziewicze narodziny, cuda Jezusa (uzdrawianie, wskrzeszanie), Jego pobożność. Islam nie akceptuje: boskości Jezusa, Trójcy Świętej i ukrzyżowania (w islamie Jezus został wzięty do nieba przez Allaha). Powróci przed Dniem Sądu — to ważna eschatologia islamska.",
    aEn: "Jesus — Isa ibn Maryam (Jesus son of Mary) — is one of the five greatest prophets in Islam (alongside Noah, Abraham, Moses and Muhammad). Islam confirms: virgin birth, Jesus's miracles (healing, raising the dead), His piety. Islam does not accept: the divinity of Jesus, the Holy Trinity, or the crucifixion (in Islam Jesus was taken to heaven by Allah). He will return before the Day of Judgement — this is important Islamic eschatology.",
    ref: "Quran 3:45-48, 4:157-158" },
  { id: "mary", tab: "religions", verdict: "info",
    qPl: "Co Quran mówi o Maryi (Maryam)?",
    qEn: "What does the Quran say about Mary (Maryam)?",
    aPl: "Rozdział 19 Qur'anu nosi imię «Maryam» — dedykowany Maryi. Maryja jest wymieniana w Qur'anie więcej razy niż w całym Nowym Testamencie. Jest uważana za czystą (al-Batool) i najlepszą z kobiet świata — według hadisu Proroka ﷺ (Tirmidhi 3878). To niezwykłe: Quran oddaje jej więcej czci niż wiele kościołów chrześcijańskich.",
    aEn: "Chapter 19 of the Quran is called 'Maryam' — dedicated to Mary. Mary is mentioned in the Quran more times than in the entire New Testament. She is considered pure (al-Batool) and the best of women in the world — according to the hadith of the Prophet ﷺ (Tirmidhi 3878). Remarkably, the Quran gives her more honour than many Christian churches.",
    ref: "Quran 3:42, 19:1-35" },
  { id: "same_god", tab: "religions", verdict: "info",
    qPl: "Czy muzułmanie, chrześcijanie i żydzi czczą tego samego Boga?",
    qEn: "Do Muslims, Christians and Jews worship the same God?",
    aPl: "Tak — z islamskiej perspektywy wszyscy czcimy Boga Abrahama, Mojżesza, Jezusa i Muhammada. «Allah» to po prostu arabskie słowo oznaczające «Bóg» — arabscy chrześcijanie od wieków mówią «Allah» modląc się do Boga chrześcijaństwa. Islam, chrześcijaństwo i judaizm to religie abrahamiczne — z jednego korzenia. Różnimy się w teologii (Trójca, boskość Jezusa), ale nie w fundamentalnym obiekcie kultu.",
    aEn: "Yes — from an Islamic perspective we all worship the God of Abraham, Moses, Jesus and Muhammad. 'Allah' is simply the Arabic word for 'God' — Arab Christians have said 'Allah' for centuries when praying to the God of Christianity. Islam, Christianity and Judaism are Abrahamic religions — from one root. We differ in theology (Trinity, divinity of Jesus), but not in the fundamental object of worship.",
    ref: "Quran 29:46" },
  { id: "common_prophets", tab: "religions", verdict: "info",
    qPl: "Jacy prorocy są wspólni dla islamu, chrześcijaństwa i judaizmu?",
    qEn: "Which prophets are shared by Islam, Christianity and Judaism?",
    aPl: "Adam (Adem), Noe (Nuh), Abraham (Ibrahim), Mojżesz (Musa), Dawid (Dawud), Salomon (Sulejman), Jan Chrzciciel (Jahja), Jezus (Isa) — wszyscy są prorokami w islamie. Quran jest pełen ich historii. Muhammad ﷺ był ostatnim prorokiem — «pieczęcią proroków» (hatam al-anbiya). Ibrahim (Abraham) jest ojcem zarówno Izaaka (przodka żydów i chrześcijan) jak i Ismaela (przodka Arabów) — stąd wspólne korzenie.",
    aEn: "Adam (Adem), Noah (Nuh), Abraham (Ibrahim), Moses (Musa), David (Dawud), Solomon (Sulayman), John the Baptist (Yahya), Jesus (Isa) — all are prophets in Islam. The Quran is full of their stories. Muhammad ﷺ was the last prophet — 'the seal of the prophets' (khatam al-anbiya). Ibrahim (Abraham) is the father of both Isaac (ancestor of Jews and Christians) and Ishmael (ancestor of Arabs) — hence the shared roots.",
    ref: "Quran 2:136" },
  { id: "dietary", tab: "religions", verdict: "info",
    qPl: "Czy islamskie zasady diety są podobne do żydowskich (koszer)?",
    qEn: "Are Islamic dietary rules similar to Jewish kosher?",
    aPl: "Tak — bardzo podobne. Obie zakazują wieprzowiny i krwi. Obie wymagają specjalnego uboju (dhabihah / shechita). Obie zakazują padliny. Różnice: koszer zakazuje mieszania mięsa z nabiałem (islam nie), koszer ma inne szczegółowe przepisy. Islam pozwala jeść koszer jako dozwolone — Quran mówi: «Pożywienie Ludzi Księgi jest dla was dozwolone» (5:5).",
    aEn: "Yes — very similar. Both forbid pork and blood. Both require special slaughter (dhabihah / shechita). Both forbid carrion. Differences: kosher forbids mixing meat with dairy (Islam doesn't), kosher has other specific rules. Islam permits eating kosher as acceptable — the Quran says: 'The food of the People of the Book is permitted to you' (5:5).",
    ref: "Quran 5:5" },

  // ── terrorism ──
  { id: "isis", tab: "terrorism", verdict: "false",
    qPl: "Czy ISIS i Al-Kaida reprezentują islam?",
    qEn: "Do ISIS and Al-Qaeda represent Islam?",
    aPl: "Nie — mówi tak ponad 99% uczonych islamskich na świecie. ISIS i Al-Kaida to ruchy takfiri — ogłaszają innych muzułmanów niewiernymi (kafir), co jest wielkim grzechem w islamie. Al-Azhar w Kairze, najstarsza i najbardziej prestiżowa uczelnia islamska świata, oficjalnie orzekła że ISIS nie są muzułmanami. Ich metodologia opiera się na wyrywaniu wersetów Quran z historycznego i językowego kontekstu — coś, co każdy uczony odrzuca.",
    aEn: "No — over 99% of Islamic scholars worldwide say so. ISIS and Al-Qaeda are takfiri movements — they declare other Muslims to be unbelievers (kafir), which is a great sin in Islam. Al-Azhar in Cairo, the world's oldest and most prestigious Islamic university, officially ruled that ISIS are not Muslims. Their methodology is based on ripping Quranic verses from historical and linguistic context — something every scholar rejects.",
    ref: "Quran 5:32, Al-Azhar fatwa 2014" },
  { id: "killing", tab: "terrorism", verdict: "false",
    qPl: "Czy Quran nakazuje zabijanie niewiernych?",
    qEn: "Does the Quran command killing non-believers?",
    aPl: "Nie — «wersety miecza» zostały objawione w konkretnym kontekście militarnym w VII wieku (obrona przed atakami na nową wspólnotę). Ogólna zasada jest jasna: «Kto zabije człowieka — jakby zabił całą ludzkość» (Quran 5:32). Prorok ﷺ zakazywał zabijania kobiet, dzieci, starców i mnichów w walce (Abu Dawud 2614). Terroryzm jest haram. Samobójstwo jest haram (Quran 4:29).",
    aEn: "No — the 'sword verses' were revealed in a specific 7th-century military context (defence against attacks on the new community). The general principle is clear: 'Whoever kills a soul — it is as if he has killed all mankind' (Quran 5:32). The Prophet ﷺ forbade killing women, children, the elderly and monks in combat (Abu Dawud 2614). Terrorism is haram. Suicide is haram (Quran 4:29).",
    ref: "Quran 5:32, 4:29" },
  { id: "jihad", tab: "terrorism", verdict: "complex",
    qPl: "Co tak naprawdę znaczy dżihad?",
    qEn: "What does jihad actually mean?",
    aPl: "Dżihad (جِهَاد) znaczy «wysiłek» lub «staranie» — od arabskiego korzenia jahada. Większy dżihad (al-jihad al-akbar) to walka z własnym ego, pożądaniem i lenistwem. Mniejszy dżihad (al-jihad al-asghar) to obrona militarna — tylko jako samoobrona, z surowymi zasadami (nie wolno krzywdzić cywilów). ISIS i media zawłaszczyły słowo «dżihad» i wypełniły je swoją propagandą — to nie jest islamska definicja.",
    aEn: "Jihad (جِهَاد) means 'struggle' or 'striving' — from the Arabic root jahada. The greater jihad (al-jihad al-akbar) is the struggle against one's own ego, desires and laziness. The lesser jihad (al-jihad al-asghar) is military defence — only as self-defence, with strict rules (civilians must not be harmed). ISIS and the media have hijacked the word 'jihad' and filled it with their propaganda — that is not the Islamic definition.",
    ref: "Tirmidhi 1621" },
  { id: "suicide_bombing", tab: "terrorism", verdict: "false",
    qPl: "Czy samobójcze zamachy są dozwolone w islamie?",
    qEn: "Are suicide bombings permitted in Islam?",
    aPl: "Absolutnie nie — podwójnie haram. Po pierwsze: samobójstwo jest haram: «Nie zabijajcie siebie samych — Allah jest dla was miłosierny» (Quran 4:29). Po drugie: mordowanie niewinnych cywilów jest haram. Hadis mówi, że ktoś kto popełni samobójstwo będzie powtarzał ten czyn w piekle (Bukhari 5778). Żaden uznaany uczony islamski na świecie nie popiera zamachów samobójczych wobec cywilów.",
    aEn: "Absolutely not — doubly haram. First: suicide is haram: 'Do not kill yourselves — Allah is merciful to you' (Quran 4:29). Second: murdering innocent civilians is haram. A hadith says that someone who commits suicide will repeat the act in hell (Bukhari 5778). No recognised Islamic scholar in the world endorses suicide bombings against civilians.",
    ref: "Quran 4:29, Bukhari 5778" }
];

