export const arabicAlphabet = [
  { id: "alif", arabicName: "ألف", polishName: "Alif", transliteration: "a / aa", forms: { isolated: "ا", initial: "ا", medial: "ـا", final: "ـا" }, pronunciation: "Długi lub krótki dźwięk a. Sama litera nie łączy się z następną po lewej stronie.", example: { ar: "إسلام", pl: "islam", tr: "islam" } },
  { id: "ba", arabicName: "باء", polishName: "Ba", transliteration: "b", forms: { isolated: "ب", initial: "بـ", medial: "ـبـ", final: "ـب" }, pronunciation: "Jak polskie b w słowie balon. Kropka znajduje się pod literą.", example: { ar: "باتيك", pl: "batik", tr: "batik" } },
  { id: "ta", arabicName: "تاء", polishName: "Ta", transliteration: "t", forms: { isolated: "ت", initial: "تـ", medial: "ـتـ", final: "ـت" }, pronunciation: "Jak polskie t. Dwie kropki są nad literą.", example: { ar: "تمر", pl: "daktyle", tr: "tamr" } },
  { id: "tha", arabicName: "ثاء", polishName: "Sa miękkie", transliteration: "th", forms: { isolated: "ث", initial: "ثـ", medial: "ـثـ", final: "ـث" }, pronunciation: "Jak angielskie th w think. Czubek języka lekko dotyka zębów.", example: { ar: "ثلج", pl: "śnieg", tr: "thalj" } },
  { id: "jim", arabicName: "جيم", polishName: "Dżim", transliteration: "j", forms: { isolated: "ج", initial: "جـ", medial: "ـجـ", final: "ـج" }, pronunciation: "Najczęściej jak polskie dż w dżem.", example: { ar: "جاوة", pl: "Jawa", tr: "jawa" } },
  { id: "ha", arabicName: "حاء", polishName: "Ha gardłowe", transliteration: "h", forms: { isolated: "ح", initial: "حـ", medial: "ـحـ", final: "ـح" }, pronunciation: "Mocne, bezdźwięczne h z gardła. Nie ma polskiego odpowiednika.", example: { ar: "حلال", pl: "halal", tr: "halal" } },
  { id: "kha", arabicName: "خاء", polishName: "Cha", transliteration: "kh", forms: { isolated: "خ", initial: "خـ", medial: "ـخـ", final: "ـخ" }, pronunciation: "Jak polskie ch, ale głębiej w gardle.", example: { ar: "خبز", pl: "chleb", tr: "chubz" } },
  { id: "dal", arabicName: "دال", polishName: "Dal", transliteration: "d", forms: { isolated: "د", initial: "د", medial: "ـد", final: "ـد" }, pronunciation: "Jak polskie d. Nie łączy się z następną literą.", example: { ar: "دعاء", pl: "dua", tr: "du'a" } },
  { id: "dhal", arabicName: "ذال", polishName: "Zal", transliteration: "dh", forms: { isolated: "ذ", initial: "ذ", medial: "ـذ", final: "ـذ" }, pronunciation: "Jak angielskie th w this. Brzmi miękko, między d i z.", example: { ar: "ذهب", pl: "złoto", tr: "dhahab" } },
  { id: "ra", arabicName: "راء", polishName: "Ra", transliteration: "r", forms: { isolated: "ر", initial: "ر", medial: "ـر", final: "ـر" }, pronunciation: "Drżące r, podobne do polskiego. Nie łączy się z następną literą.", example: { ar: "رمضان", pl: "ramadan", tr: "ramadan" } },
  { id: "zay", arabicName: "زاي", polishName: "Zaj", transliteration: "z", forms: { isolated: "ز", initial: "ز", medial: "ـز", final: "ـز" }, pronunciation: "Jak polskie z. Nie łączy się z następną literą.", example: { ar: "زيارة", pl: "wizyta", tr: "zijara" } },
  { id: "sin", arabicName: "سين", polishName: "Sin", transliteration: "s", forms: { isolated: "س", initial: "سـ", medial: "ـسـ", final: "ـس" }, pronunciation: "Jak polskie s.", example: { ar: "سلام", pl: "pokój, salam", tr: "salam" } },
  { id: "shin", arabicName: "شين", polishName: "Szin", transliteration: "sh", forms: { isolated: "ش", initial: "شـ", medial: "ـشـ", final: "ـش" }, pronunciation: "Jak polskie sz.", example: { ar: "شمس", pl: "słońce", tr: "szams" } },
  { id: "sad", arabicName: "صاد", polishName: "Sad", transliteration: "s", forms: { isolated: "ص", initial: "صـ", medial: "ـصـ", final: "ـص" }, pronunciation: "Głębokie, ciemne s wymawiane z napięciem w jamie ustnej.", example: { ar: "صلاة", pl: "modlitwa", tr: "salat" } },
  { id: "dad", arabicName: "ضاد", polishName: "Dad", transliteration: "d", forms: { isolated: "ض", initial: "ضـ", medial: "ـضـ", final: "ـض" }, pronunciation: "Głębokie d, charakterystyczne dla arabskiego.", example: { ar: "ضيف", pl: "gość", tr: "dajf" } },
  { id: "ta_emph", arabicName: "طاء", polishName: "Ta głębokie", transliteration: "t", forms: { isolated: "ط", initial: "طـ", medial: "ـطـ", final: "ـط" }, pronunciation: "Głębokie, mocne t.", example: { ar: "طعام", pl: "jedzenie", tr: "ta'am" } },
  { id: "za_emph", arabicName: "ظاء", polishName: "Za głębokie", transliteration: "z / dh", forms: { isolated: "ظ", initial: "ظـ", medial: "ـظـ", final: "ـظ" }, pronunciation: "Głębokie brzmienie między z i angielskim th.", example: { ar: "ظاهر", pl: "widoczny", tr: "zahir" } },
  { id: "ayn", arabicName: "عين", polishName: "Ajn", transliteration: "'", forms: { isolated: "ع", initial: "عـ", medial: "ـعـ", final: "ـع" }, pronunciation: "Dźwięk gardłowy, jak napięte a zaczynane głęboko w gardle.", example: { ar: "علم", pl: "wiedza", tr: "'ilm" } },
  { id: "ghayn", arabicName: "غين", polishName: "Gajn", transliteration: "gh", forms: { isolated: "غ", initial: "غـ", medial: "ـغـ", final: "ـغ" }, pronunciation: "Dźwięczne, gardłowe r/ch, podobne do francuskiego r.", example: { ar: "غدانسك", pl: "Gdańsk", tr: "ghdansk" } },
  { id: "fa", arabicName: "فاء", polishName: "Fa", transliteration: "f", forms: { isolated: "ف", initial: "فـ", medial: "ـفـ", final: "ـف" }, pronunciation: "Jak polskie f.", example: { ar: "فجر", pl: "świt", tr: "fadżr" } },
  { id: "qaf", arabicName: "قاف", polishName: "Kaf głębokie", transliteration: "q", forms: { isolated: "ق", initial: "قـ", medial: "ـقـ", final: "ـق" }, pronunciation: "Głębokie k wymawiane z tyłu języka.", example: { ar: "قرآن", pl: "Koran", tr: "qur'an" } },
  { id: "kaf", arabicName: "كاف", polishName: "Kaf", transliteration: "k", forms: { isolated: "ك", initial: "كـ", medial: "ـكـ", final: "ـك" }, pronunciation: "Jak polskie k.", example: { ar: "كتاب", pl: "książka", tr: "kitab" } },
  { id: "lam", arabicName: "لام", polishName: "Lam", transliteration: "l", forms: { isolated: "ل", initial: "لـ", medial: "ـلـ", final: "ـل" }, pronunciation: "Jak polskie l.", example: { ar: "لوبلين", pl: "Lublin", tr: "lublin" } },
  { id: "mim", arabicName: "ميم", polishName: "Mim", transliteration: "m", forms: { isolated: "م", initial: "مـ", medial: "ـمـ", final: "ـم" }, pronunciation: "Jak polskie m.", example: { ar: "مسجد", pl: "meczet", tr: "masdżid" } },
  { id: "nun", arabicName: "نون", polishName: "Nun", transliteration: "n", forms: { isolated: "ن", initial: "نـ", medial: "ـنـ", final: "ـن" }, pronunciation: "Jak polskie n.", example: { ar: "إندونيسيا", pl: "Indonezja", tr: "indunisia" } },
  { id: "ha2", arabicName: "هاء", polishName: "Ha lekkie", transliteration: "h", forms: { isolated: "ه", initial: "هـ", medial: "ـهـ", final: "ـه" }, pronunciation: "Lekkie h, podobne do polskiego h w herbata.", example: { ar: "هلال", pl: "półksiężyc", tr: "hilal" } },
  { id: "waw", arabicName: "واو", polishName: "Ław", transliteration: "w / u", forms: { isolated: "و", initial: "و", medial: "ـو", final: "ـو" }, pronunciation: "Jak angielskie w albo długie u. Nie łączy się z następną literą.", example: { ar: "وارسو", pl: "Warszawa", tr: "warsaw" } },
  { id: "ya", arabicName: "ياء", polishName: "Ja", transliteration: "y / i", forms: { isolated: "ي", initial: "يـ", medial: "ـيـ", final: "ـي" }, pronunciation: "Jak j albo długie i.", example: { ar: "يوغياكارتا", pl: "Yogyakarta", tr: "jogyakarta" } }
];

export const words = [
  { id: "mama", ar: "ماما", tr: "mama", pl: "mama" },
  { id: "baba", ar: "بابا", tr: "baba", pl: "tata / baba" },
  { id: "kitab", ar: "كتاب", tr: "kitab", pl: "książka" },
  { id: "bait", ar: "بيت", tr: "bajt", pl: "dom" },
  { id: "shams", ar: "شمس", tr: "szams", pl: "słońce" },
  { id: "qamar", ar: "قمر", tr: "kamar", pl: "księżyc" },
  { id: "salam", ar: "سلام", tr: "salam", pl: "pokój / cześć" },
  { id: "islam", ar: "إسلام", tr: "islam", pl: "islam" },
  { id: "quran", ar: "قرآن", tr: "Koran", pl: "Koran" },
  { id: "masjid", ar: "مسجد", tr: "masdżid", pl: "meczet" },
  { id: "polska", ar: "بولندا", tr: "bulanda", pl: "Polska" },
  { id: "warsaw", ar: "وارسو", tr: "warsaw", pl: "Warszawa" },
  { id: "lublin", ar: "لوبلين", tr: "lublin", pl: "Lublin" },
  { id: "indonesia", ar: "إندونيسيا", tr: "indunisia", pl: "Indonezja" },
  { id: "batik", ar: "باتيك", tr: "batik", pl: "batik" },
  { id: "borobudur", ar: "بوروبودور", tr: "borobudur", pl: "Borobudur" },
  { id: "orangutan", ar: "أورانغوتان", tr: "orangutan", pl: "orangutan" },
  { id: "pierogi", ar: "بيروغي", tr: "pierogi", pl: "pierogi" },
  { id: "zloty", ar: "زلوتي", tr: "zloty", pl: "złoty" },
  { id: "halal", ar: "حلال", tr: "halal", pl: "halal" },
  { id: "rahma", ar: "رحمة", tr: "rahma", pl: "miłosierdzie" },
  { id: "nur", ar: "نور", tr: "nur", pl: "światło" },
  { id: "woda", ar: "ماء", tr: "ma", pl: "woda" },
  { id: "ryz", ar: "أرز", tr: "aruzz", pl: "ryż" }
];

export const dailyTasks = [
  "Poznaj 3 nowe litery i kliknij każdą z nich.",
  "Zrób 7 fiszek w trybie powtórek.",
  "Przećwicz wymowę słowa سلام.",
  "Narysuj literę ب na canvasie.",
  "Zagraj jedną rundę Memory Match."
];
