// How-to-pray data: 5 daily prayers in Sunni tradition with rakah counts and step-by-step movements.
// Sources: Sahih al-Bukhari, Sahih Muslim, Sunan Abu Dawud (standard Sunni fiqh).

export const prayerInfo = {
  pl: {
    intro: "Modlitwa (salah) to filar islamu. Jej ruchy odzwierciedlają pokorę, wdzięczność i poddanie się Allahowi.",
    rakahNote: "Rakah (jednostka modlitwy) to cykl: stanie → pokłon → 2 prosternacje. Liczba rakat zależy od modlitwy.",
    prayers: [
      { key: "Fajr",    namePl: "Fajr",    timePl: "Świt — przed wschodem słońca", fardRakah: 2, sunnah: "2 rak'ah sunnah PRZED" },
      { key: "Dhuhr",   namePl: "Dhuhr",   timePl: "Po zenicie do połowy popołudnia", fardRakah: 4, sunnah: "4 rak'ah przed + 2 po" },
      { key: "Asr",     namePl: "Asr",     timePl: "Późne popołudnie do zachodu", fardRakah: 4, sunnah: "4 rak'ah przed (mustahab)" },
      { key: "Maghrib", namePl: "Maghrib", timePl: "Tuż po zachodzie słońca", fardRakah: 3, sunnah: "2 rak'ah po" },
      { key: "Isha",    namePl: "Isha",    timePl: "Po zniknięciu czerwonej zorzy do północy", fardRakah: 4, sunnah: "2 rak'ah po + 3 Witr" }
    ],
    prereq: [
      { id: "wudu", title: "1. Wudu — ablucja", desc: "Umyj: ręce 3× → usta 3× → nos 3× → twarz 3× → ręce do łokcia (prawa, lewa) 3× → przetrzyj głowę 1× → uszy 1× → stopy do kostek (prawa, lewa) 3×. Wymów bismillah na początku." },
      { id: "wear", title: "2. Czyste ubranie i miejsce", desc: "Ubranie i miejsce modlitwy muszą być czyste. Mężczyzna: pokryty od pępka do kolan minimum (lepiej cały tors). Kobieta: pokryte całe ciało poza twarzą i dłońmi." },
      { id: "qibla", title: "3. Skierowanie do Mekki (qibla)", desc: "Stań twarzą w stronę Kaaby. W aplikacji w sekcji Modlitwy znajdziesz strzałkę qibla z kompasem." },
      { id: "niyyah", title: "4. Intencja (niyyah)", desc: "W sercu (nie trzeba na głos) powiedz: «Modlę się [Fajr/Dhuhr/...] dla Allaha, [N] rak'ah, fard»." }
    ],
    steps: [
      { id: "takbir", icon: "🤲", title: "1. Takbiratul-Ihram (otwarcie)",
        body: "Stań prosto, ręce wzdłuż ciała. Podnieś obie ręce do uszu i powiedz głośno «Allahu Akbar». Połóż prawą dłoń na lewej na piersi (Hanbali) lub na pępku (Hanafi).",
        words_ar: "اللهُ أَكْبَر", words_tr: "Allahu Akbar", words_pl: "Bóg jest Największy",
        sunnah: "Hanbali/Shafi'i: ręce na piersi. Hanafi: pod pępkiem. Maliki: opuszczone wzdłuż ciała." },
      { id: "qiyam", icon: "🧍", title: "2. Qiyam (stanie)",
        body: "Stojąc, recytuj: Du'a otwierający (opcjonalnie), potem Surah Al-Fatihah (obowiązkowo w każdej rak'ah), potem dowolną krótką surę (w 1. i 2. rak'ah).",
        words_ar: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ...",
        words_tr: "Bismillahir-Rahmanir-Rahim. Alhamdulillahi Rabbil-'alamin...",
        words_pl: "W imię Boga Miłosiernego, Litościwego. Chwała Bogu, Panu światów..." },
      { id: "ruku", icon: "🙇", title: "3. Ruku (pokłon)",
        body: "Powiedz «Allahu Akbar», pochyl się w pasie. Ręce na kolanach, plecy proste i równolegle do ziemi. Powtórz 3× «Subhana Rabbiyal-Azim».",
        words_ar: "سُبْحَانَ رَبِّيَ الْعَظِيم", words_tr: "Subhana Rabbiyal-Azim", words_pl: "Chwała mojemu Panu Najwyższemu" },
      { id: "itidal", icon: "🧎‍♂️", title: "4. I'tidal (powrót do stania)",
        body: "Wstań, ręce opuszczone lub złożone (madhhab). Powiedz: «Sami' Allahu liman hamidah», potem: «Rabbana wa lakal-hamd».",
        words_ar: "سَمِعَ اللَّهُ لِمَنْ حَمِدَه ۞ رَبَّنَا وَلَكَ الْحَمْد",
        words_tr: "Sami' Allahu liman hamidah, Rabbana wa lakal-hamd",
        words_pl: "Allah słyszy tego, który Go chwali, Panie nasz i dla Ciebie chwała" },
      { id: "sujud1", icon: "🙏", title: "5. Sujud (prosternacja, 1×)",
        body: "Powiedz «Allahu Akbar», zegnij się: kolana → ręce → czoło i nos dotykają ziemi. Łokcie nie dotykają ziemi. Powtórz 3× «Subhana Rabbiyal-A'la».",
        words_ar: "سُبْحَانَ رَبِّيَ الأَعْلَى", words_tr: "Subhana Rabbiyal-A'la", words_pl: "Chwała mojemu Panu Najwyższemu",
        sunnah: "7 części ciała dotyka podłogi: czoło + nos, dwie dłonie, dwa kolana, palce obu stóp." },
      { id: "jalsa", icon: "🪑", title: "6. Jalsa (siedzenie między prosternacjami)",
        body: "Wstań do siedzenia, lewa stopa zgięta, prawa pionowo. Ręce na udach. Powiedz: «Rabbighfirli» (Panie, przebacz mi).",
        words_ar: "رَبِّ اغْفِرْ لِي", words_tr: "Rabbighfirli", words_pl: "Panie, przebacz mi" },
      { id: "sujud2", icon: "🙏", title: "7. Druga prosternacja (sujud 2)",
        body: "Powtórz prosternację jak w kroku 5. Drugi sujud kończy 1 rak'ah.",
        words_ar: "سُبْحَانَ رَبِّيَ الأَعْلَى", words_tr: "Subhana Rabbiyal-A'la", words_pl: "Chwała mojemu Panu Najwyższemu" },
      { id: "next_rakah", icon: "🔁", title: "8. Wstań do kolejnej rak'ah",
        body: "Powiedz «Allahu Akbar» wstając. Powtórz kroki 2–7 dla każdej kolejnej rak'ah. W 2. rak'ah można recytować inną krótką surę. Po 2 rak'ah usiądź do tashahhud." },
      { id: "tashahhud", icon: "🪑", title: "9. Tashahhud (świadectwo, w siedzeniu)",
        body: "Po 2. rak'ah usiądź. Recytuj: «At-tahiyyatu lillah, was-salawatu wat-tayyibat...». Wskaż palcem wskazującym prawej ręki przy «la ilaha illa Allah».",
        words_ar: "التَّحِيَّاتُ لِلَّهِ ... أَشْهَدُ أَن لاَ إِلَٰهَ إِلاَّ اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
        words_tr: "At-tahiyyatu lillah... ashhadu an la ilaha illa Allah, wa ashhadu anna Muhammadan abduhu wa rasuluh",
        words_pl: "Pozdrowienia są dla Allaha... Świadczę, że nie ma boga prócz Allaha i że Muhammad jest Jego sługą i posłańcem" },
      { id: "salawat", icon: "💗", title: "10. Salawat (po ostatnim tashahhud)",
        body: "W ostatniej rak'ah po tashahhud dodaj salawat na Proroka ﷺ:",
        words_ar: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ ...",
        words_tr: "Allahumma salli 'ala Muhammad wa 'ala ali Muhammad...",
        words_pl: "Allahu, błogosław Muhammada i ród Muhammada..." },
      { id: "salam", icon: "🕊️", title: "11. Taslim (zakończenie)",
        body: "Obróć głowę w prawo: «As-salamu alaykum wa rahmatullah». W lewo: to samo. Modlitwa zakończona.",
        words_ar: "السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللَّه", words_tr: "As-salamu alaykum wa rahmatullah", words_pl: "Pokój wam i miłosierdzie Allaha" }
    ],
    after: [
      "Astaghfirullah × 3 — proszę Allaha o przebaczenie",
      "Allahumma anta as-Salam wa minka as-Salam — Boże, Tyś Pokojem i od Ciebie pokój",
      "Subhanallah × 33, Alhamdulillah × 33, Allahu Akbar × 34 (lub 33+33+33 + La ilaha illa Allah × 1)",
      "Ayat al-Kursi (2:255) — chroni do następnej modlitwy",
      "Du'a osobista — proś Allaha o cokolwiek po arabsku lub w swoim języku"
    ]
  },
  en: {
    intro: "Salah (prayer) is a pillar of Islam. Its movements reflect humility, gratitude, and submission to Allah.",
    rakahNote: "A rak'ah (prayer unit) is a cycle: standing → bowing → 2 prostrations. The number of rak'ahs depends on the prayer.",
    prayers: [
      { key: "Fajr",    namePl: "Fajr",    timePl: "Dawn — before sunrise", fardRakah: 2, sunnah: "2 rak'ah sunnah BEFORE" },
      { key: "Dhuhr",   namePl: "Dhuhr",   timePl: "After zenith until mid-afternoon", fardRakah: 4, sunnah: "4 rak'ah before + 2 after" },
      { key: "Asr",     namePl: "Asr",     timePl: "Late afternoon until sunset", fardRakah: 4, sunnah: "4 rak'ah before (mustahab)" },
      { key: "Maghrib", namePl: "Maghrib", timePl: "Right after sunset", fardRakah: 3, sunnah: "2 rak'ah after" },
      { key: "Isha",    namePl: "Isha",    timePl: "After red glow disappears until midnight", fardRakah: 4, sunnah: "2 rak'ah after + 3 Witr" }
    ],
    prereq: [
      { id: "wudu", title: "1. Wudu — ablution", desc: "Wash: hands 3× → mouth 3× → nose 3× → face 3× → arms to elbow (right, left) 3× → wipe head 1× → ears 1× → feet to ankles (right, left) 3×. Say bismillah at the start." },
      { id: "wear", title: "2. Clean clothes & place", desc: "Both clothing and prayer space must be clean. Men: covered from navel to knee minimum (whole torso preferred). Women: whole body covered except face and hands." },
      { id: "qibla", title: "3. Face Mecca (qibla)", desc: "Stand facing the Kaaba. The Prayers section in this app shows a qibla arrow with compass." },
      { id: "niyyah", title: "4. Intention (niyyah)", desc: "In your heart (no need to speak), say: 'I am praying [Fajr/Dhuhr/...] for Allah, [N] rak'ahs, fard.'" }
    ],
    steps: [
      { id: "takbir", icon: "🤲", title: "1. Takbiratul-Ihram (opening)",
        body: "Stand straight, arms at sides. Raise both hands to your ears and say aloud 'Allahu Akbar'. Place right hand over left on chest (Hanbali) or below navel (Hanafi).",
        words_ar: "اللهُ أَكْبَر", words_tr: "Allahu Akbar", words_pl: "Allah is the Greatest",
        sunnah: "Hanbali/Shafi'i: hands on chest. Hanafi: below navel. Maliki: at sides." },
      { id: "qiyam", icon: "🧍", title: "2. Qiyam (standing)",
        body: "While standing, recite: opening du'a (optional), then Al-Fatihah (mandatory in every rak'ah), then any short surah (in 1st and 2nd rak'ah only).",
        words_ar: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ...",
        words_tr: "Bismillahir-Rahmanir-Rahim. Alhamdulillahi Rabbil-'alamin...",
        words_pl: "In the name of Allah, the Most Merciful. All praise to Allah, Lord of the worlds..." },
      { id: "ruku", icon: "🙇", title: "3. Ruku (bowing)",
        body: "Say 'Allahu Akbar' and bow at the waist. Hands on knees, back straight and parallel to the ground. Repeat 3× 'Subhana Rabbiyal-Azim'.",
        words_ar: "سُبْحَانَ رَبِّيَ الْعَظِيم", words_tr: "Subhana Rabbiyal-Azim", words_pl: "Glory to my Lord, the Most Great" },
      { id: "itidal", icon: "🧎‍♂️", title: "4. I'tidal (return to standing)",
        body: "Stand up. Say: 'Sami' Allahu liman hamidah', then 'Rabbana wa lakal-hamd'.",
        words_ar: "سَمِعَ اللَّهُ لِمَنْ حَمِدَه ۞ رَبَّنَا وَلَكَ الْحَمْد",
        words_tr: "Sami' Allahu liman hamidah, Rabbana wa lakal-hamd",
        words_pl: "Allah hears those who praise Him; our Lord, and to You is praise" },
      { id: "sujud1", icon: "🙏", title: "5. Sujud (prostration, 1st)",
        body: "Say 'Allahu Akbar', go down: knees → hands → forehead and nose touch the ground. Elbows do NOT touch the ground. Repeat 3× 'Subhana Rabbiyal-A'la'.",
        words_ar: "سُبْحَانَ رَبِّيَ الأَعْلَى", words_tr: "Subhana Rabbiyal-A'la", words_pl: "Glory to my Lord, the Most High",
        sunnah: "7 body parts touch the floor: forehead + nose, two palms, two knees, toes of both feet." },
      { id: "jalsa", icon: "🪑", title: "6. Jalsa (sitting between prostrations)",
        body: "Sit up: left foot folded, right foot vertical. Hands on thighs. Say: 'Rabbighfirli' (Lord, forgive me).",
        words_ar: "رَبِّ اغْفِرْ لِي", words_tr: "Rabbighfirli", words_pl: "My Lord, forgive me" },
      { id: "sujud2", icon: "🙏", title: "7. Second prostration (sujud 2)",
        body: "Repeat the prostration as in step 5. The second sujud completes 1 rak'ah.",
        words_ar: "سُبْحَانَ رَبِّيَ الأَعْلَى", words_tr: "Subhana Rabbiyal-A'la", words_pl: "Glory to my Lord, the Most High" },
      { id: "next_rakah", icon: "🔁", title: "8. Stand for the next rak'ah",
        body: "Say 'Allahu Akbar' as you rise. Repeat steps 2–7 for each subsequent rak'ah. In the 2nd rak'ah you may recite a different short surah. After 2 rak'ahs, sit for tashahhud." },
      { id: "tashahhud", icon: "🪑", title: "9. Tashahhud (testimony, sitting)",
        body: "After the 2nd rak'ah, sit. Recite: 'At-tahiyyatu lillah, was-salawatu wat-tayyibat...'. Point with the right index finger at 'la ilaha illa Allah'.",
        words_ar: "التَّحِيَّاتُ لِلَّهِ ... أَشْهَدُ أَن لاَ إِلَٰهَ إِلاَّ اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
        words_tr: "At-tahiyyatu lillah... ashhadu an la ilaha illa Allah, wa ashhadu anna Muhammadan abduhu wa rasuluh",
        words_pl: "Greetings are for Allah... I bear witness there is no god but Allah, and Muhammad is His servant and messenger" },
      { id: "salawat", icon: "💗", title: "10. Salawat (after the final tashahhud)",
        body: "In the final rak'ah after tashahhud, add salawat upon the Prophet ﷺ:",
        words_ar: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ ...",
        words_tr: "Allahumma salli 'ala Muhammad wa 'ala ali Muhammad...",
        words_pl: "O Allah, send blessings upon Muhammad and the family of Muhammad..." },
      { id: "salam", icon: "🕊️", title: "11. Taslim (closing)",
        body: "Turn your head to the right: 'As-salamu alaykum wa rahmatullah'. Then to the left: same. The prayer is complete.",
        words_ar: "السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللَّه", words_tr: "As-salamu alaykum wa rahmatullah", words_pl: "Peace be upon you and Allah's mercy" }
    ],
    after: [
      "Astaghfirullah × 3 — I seek Allah's forgiveness",
      "Allahumma anta as-Salam wa minka as-Salam — O Allah, You are Peace and from You is peace",
      "Subhanallah × 33, Alhamdulillah × 33, Allahu Akbar × 34 (or 33+33+33 + La ilaha illa Allah × 1)",
      "Ayat al-Kursi (2:255) — protects until the next prayer",
      "Personal du'a — ask Allah for anything in Arabic or your language"
    ]
  }
};
